package main

import (
	"database/sql"
	"fmt"
	"github.com/google/uuid"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	topics := []string{
		//"Efectos Psicológicos del Acoso Escolar: Caminos hacia la Depresión",
		//"Impacto del Acoso Cibernético en la Salud Mental: Casos de Depresión",
		//"Depresión y Acoso en el Entorno Laboral: Testimonios Reales",
		//"Historias de Depresión por Acoso en Redes Sociales: Un Análisis Personal",
		//"Experiencias de Depresión en Víctimas de Acoso en Espacios Públicos",
		//"Relatos de Depresión y Acoso en Instituciones Educativas",
		//"El Ciclo de Acoso y Depresión: Cómo la Violencia Psicológica Afecta la Salud Mental",
		//"Testimonios de Depresión en Mujeres Adultas Tras Experiencias de Acoso",
		//"Acoso y Depresión en Jóvenes: Historias de Superación y Resiliencia",
		//"Cómo el Acoso Emocional Conduce a la Depresión: Experiencias en el Ámbito Familiar",
		//"Crónicas de Depresión en Víctimas de Acoso en el Trabajo: Un Enfoque Integral",
		//"Narrativas de Depresión y Bullying Escolar: Impacto a Largo Plazo",
		//"Historias de Depresión por Acoso en Espacios Recreativos: Efectos en la Autoestima",
		//"El Rol del Acoso en la Aparición de Trastornos Depresivos: Casos Documentados",
		//"Depresión Asociada al Acoso Sexual en Ambientes Académicos: Testimonios Personales",
		//"Foros de Víctimas de Acoso: Discusiones sobre la Relación con la Depresión",
		//"Relatos de Acoso en la Comunidad Virtual y su Impacto en la Salud Mental",
		//"Historias de Depresión en Adolescentes Víctimas de Acoso Escolar",
		//"Casos Reales de Depresión como Consecuencia de Acoso en Centros de Fitness",
		//"El Impacto del Acoso Psicológico en la Salud Mental: Historias de Depresión",
		//"Testimonios de Depresión Tras Experiencias de Acoso en Barrios",
		//"Narrativas de Depresión en Víctimas de Acoso en Colegios",
		//"Historias de Acoso en Espacios Laborales y sus Efectos Depresivos",
		//"Depresión y Acoso en Universidades: Testimonios de Estudiantes",
		//"Relatos de Depresión por Acoso en Centros Comerciales y Espacios Públicos",
		//"Casos de Depresión en Víctimas de Acoso en el Transporte Público",
		//"Crónicas de Depresión en Víctimas de Acoso Emocional en el Hogar",
		//"Experiencias de Depresión en Víctimas de Acoso en Plazas Públicas",
		//"Historias de Acoso Sexual y su Impacto en la Salud Mental: Casos de Depresión",
		//"El Efecto del Acoso en la Autoestima y su Relación con la Depresión",
		//"Narrativas de Depresión en Víctimas de Acoso en el Ámbito Deportivo",
		//"Historias de Acoso en Instituciones Educativas y su Relación con Trastornos Depresivos",
		//"Depresión y Acoso en la Comunidad: Casos y Testimonios",
		//"Foros sobre Acoso y Depresión: Testimonios de Víctimas",
		//"Relatos de Depresión en Víctimas de Acoso en Entornos Recreativos",
		//"Impacto del Acoso en la Salud Mental de Adultos Mayores: Historias de Depresión",
		//"Historias de Depresión por Acoso en la Red: Testimonios de Superación",
		//"Relatos de Depresión en Víctimas de Acoso en la Calle",
		//"Experiencias de Depresión en Víctimas de Acoso en Gimnasios y Centros de Fitness",
		//"El Rol del Acoso Psicológico en la Aparición de Trastornos Depresivos: Casos Reales",
		//"Impacto Psicológico de la Violación y el Acoso: Historias de Supervivencia",
		//"Experiencias de Violación y Acoso en Ambientes Educativos: Un Análisis Profundo",
		//"Testimonios de Violación y Acoso en el Trabajo: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso en Víctimas de Violación: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Violación y Acoso en la Comunidad Virtual: Impacto en la Salud Mental",
		//"Crónicas de Violación y Acoso en Instituciones Educativas: Efectos Psicológicos",
		//"Relatos de Violación y Acoso en Redes Sociales: Impacto en las Víctimas",
		//"Historias de Violación y Acoso en el Transporte Público: Testimonios de Víctimas",
		//"Casos Documentados de Violación y Acoso en Espacios Recreativos",
		//"El Rol del Acoso en Casos de Violación: Análisis de Efectos Psicológicos",
		//"Testimonios de Violación y Acoso en Barrios: Consecuencias a Largo Plazo",
		//"Violación y Acoso en Entornos Laborales: Impacto en la Salud Mental de los Empleados",
		//"Historias de Violación y Acoso en Instituciones de Educación Superior",
		//"Experiencias de Violación y Acoso en Ámbitos Deportivos: Testimonios Reales",
		//"El Impacto de la Violación y el Acoso en la Autoestima: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Plazas Públicas: Consecuencias Emocionales",
		//"Violación y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Historias de Violación y Acoso en Centros Comerciales: Casos y Reflexiones",
		//"Relatos de Violación y Acoso en Centros de Fitness: Impacto Psicológico en las Víctimas",
		//"Testimonios de Violación y Acoso en la Calle: Consecuencias para la Salud Mental",
		//"Violación y Acoso en Universidades: Un Estudio de Casos y Testimonios",
		//"El Efecto del Acoso Sexual en Casos de Violación: Experiencias y Consecuencias",
		//"Narrativas de Violación y Acoso en Espacios Laborales: Impacto en la Vida Profesional",
		//"Historias de Violación y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Casos Reales de Violación y Acoso en el Ámbito Educativo: Testimonios de Supervivientes",
		//"El Impacto del Acoso en Víctimas de Violación en el Ámbito Familiar",
		//"Experiencias de Violación y Acoso en Gimnasios: Consecuencias Emocionales",
		//"Historias de Violación y Acoso en Espacios Públicos: Un Análisis de Casos",
		//"Violación y Acoso en Foros de Víctimas: Discusiones sobre Impacto Psicológico",
		//"Relatos de Violación y Acoso en Espacios Recreativos: Impacto en la Salud Mental",
		//"Testimonios de Violación y Acoso en Instituciones de Salud: Consecuencias y Reflexiones",
		//"Historias de Violación y Acoso en Colegios: Un Estudio de Casos",
		//"El Efecto del Acoso Emocional en Casos de Violación: Testimonios de Víctimas",
		//"Violación y Acoso en el Transporte Público: Casos y Efectos Psicológicos",
		//"Narrativas de Violación y Acoso en el Ámbito Social: Consecuencias para las Víctimas",
		//"Historias de Violación y Acoso en Ámbitos Académicos: Impacto en la Salud Mental",
		//"Relatos de Violación y Acoso en Espacios Privados: Consecuencias Psicológicas",
		//"Experiencias de Violación y Acoso en Comunidades Virtuales: Un Enfoque Integral",
		//"El Impacto del Acoso en Casos de Violación: Consecuencias y Reflexiones",
		//"El Impacto del Acoso en el Desarrollo de la Bulimia: Testimonios de Víctimas",
		//"Relatos de Bulimia y Acoso en Instituciones Educativas: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Experiencias de Bulimia y Acoso en Redes Sociales: Consecuencias para la Salud Mental",
		//"Acoso Escolar y Bulimia: Un Análisis de Casos y Consecuencias",
		//"El Efecto del Acoso en la Bulimia: Testimonios de Supervivientes",
		//"Narrativas de Bulimia y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Bulimia y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Historias de Bulimia y Acoso en Comunidades Virtuales: Impacto Emocional",
		//"Testimonios de Bulimia y Acoso en el Transporte Público: Un Análisis",
		//"El Rol del Acoso en Casos de Bulimia: Consecuencias Psicológicas y Emocionales",
		//"Bulimia y Acoso en Espacios Recreativos: Casos y Reflexiones",
		//"Historias de Bulimia y Acoso en Entornos Educativos: Consecuencias para la Salud Mental",
		//"El Impacto del Acoso en el Desarrollo de Trastornos Alimentarios: Un Estudio de Bulimia",
		//"Relatos de Bulimia y Acoso en Instituciones de Salud: Consecuencias Emocionales",
		//"Acoso Cibernético y Bulimia: Consecuencias para la Salud Mental",
		//"Experiencias de Bulimia y Acoso en Entornos Deportivos: Testimonios Reales",
		//"Historias de Bulimia y Acoso en Centros Comerciales: Consecuencias Psicológicas",
		//"El Efecto del Acoso en la Autoestima y la Bulimia: Un Análisis de Casos",
		//"Relatos de Bulimia y Acoso en Espacios Laborales: Impacto Emocional",
		//"Historias de Bulimia y Acoso en Ámbitos Académicos: Consecuencias Psicológicas",
		//"El Impacto del Acoso Emocional en Casos de Bulimia: Testimonios de Víctimas",
		//"Bulimia y Acoso en Foros de Víctimas: Discusiones sobre Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Sociales: Consecuencias y Reflexiones",
		//"Experiencias de Bulimia y Acoso en la Calle: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en Centros de Fitness: Impacto Psicológico",
		//"Relatos de Bulimia y Acoso en la Comunidad Virtual: Un Enfoque Integral",
		//"Bulimia y Acoso en Espacios Privados: Consecuencias para la Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Académicos: Impacto en la Autoestima",
		//"Historias de Bulimia y Acoso en Blogs: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso Escolar en la Bulimia: Testimonios y Reflexiones",
		//"Relatos de Bulimia y Acoso en el Ámbito Familiar: Consecuencias Emocionales",
		//"Historias de Bulimia y Acoso en el Ámbito Social: Un Estudio de Casos",
		//"El Impacto del Acoso en el Comportamiento Alimentario: Casos de Bulimia",
		//"Testimonios de Bulimia y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Historias de Bulimia y Acoso en Espacios Educativos: Un Análisis de Casos",
		//"El Rol del Acoso en el Desarrollo de Trastornos Alimentarios: Un Enfoque en la Bulimia",
		//"Experiencias de Bulimia y Acoso en el Transporte Público: Consecuencias Psicológicas",
		//"Relatos de Bulimia y Acoso en Entornos Deportivos: Impacto Emocional en las Víctimas",
		//"Historias de Bulimia y Acoso en Instituciones Educativas: Impacto en la Autoestima",
		//"El Impacto del Acoso en Víctimas de Abandono Familiar: Historias de Superación",
		//"Relatos de Acoso y Abandono Familiar en Entornos Educativos: Un Análisis",
		//"Acoso en el Contexto del Abandono Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso y Abandono Familiar en Jóvenes: Un Camino hacia la Resiliencia",
		//"El Rol del Acoso en Víctimas de Abandono Familiar: Casos Documentados",
		//"Testimonios de Acoso y Abandono Familiar en Espacios Públicos",
		//"Historias de Abandono Familiar y Acoso en Redes Sociales: Impacto en la Salud Mental",
		//"Acoso en Niños y Adolescentes Víctimas de Abandono Familiar: Relatos Reales",
		//"Casos de Acoso en Víctimas de Abandono Familiar en el Ámbito Educativo",
		//"El Ciclo de Acoso y Abandono Familiar: Consecuencias Psicológicas a Largo Plazo",
		//"Relatos de Abandono Familiar y Acoso en Instituciones Educativas",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en la Adolescencia",
		//"El Impacto del Abandono Familiar y el Acoso en la Autoestima: Historias Reales",
		//"Acoso y Abandono Familiar en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Narrativas de Acoso y Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Niños: Consecuencias Emocionales",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Entornos Deportivos",
		//"Relatos de Acoso en Jóvenes Víctimas de Abandono Familiar: Impacto Psicológico",
		//"El Efecto del Acoso en Niños Víctimas de Abandono Familiar: Casos Documentados",
		//"Acoso en Víctimas de Abandono Familiar en Centros de Acogida: Historias Reales",
		//"Historias de Abandono Familiar y Acoso en la Vida Adulta: Testimonios de Superación",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Transporte Público",
		//"Acoso en Víctimas de Abandono Familiar en Centros Comerciales: Un Estudio de Casos",
		//"El Impacto del Abandono Familiar y el Acoso en la Salud Mental de las Víctimas",
		//"Casos de Acoso y Abandono Familiar en el Contexto Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso en Víctimas de Abandono Familiar en Instituciones de Salud",
		//"El Ciclo de Abandono Familiar y Acoso en Niños y Adolescentes: Testimonios Reales",
		//"Acoso en Víctimas de Abandono Familiar en Espacios Recreativos: Historias Reales",
		//"El Rol del Acoso en Víctimas de Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Efectos a Largo Plazo",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Colegios",
		//"Relatos de Acoso en Niños Víctimas de Abandono Familiar en Espacios Públicos",
		//"El Impacto del Acoso en Adolescentes Víctimas de Abandono Familiar: Historias Reales",
		//"Acoso y Abandono Familiar en Jóvenes Adultos: Consecuencias Psicológicas",
		//"Historias de Abandono Familiar y Acoso en el Ámbito Académico",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Ámbito Laboral",
		//"El Efecto del Abandono Familiar en el Desarrollo de Trastornos Psicológicos Relacionados con el Acoso",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Espacios Deportivos",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Consecuencias Emocionales",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en Espacios Recreativos",
		//"Acoso Escolar en Personas Introvertidas: Impacto Psicológico",
		//"Cómo el Acoso Afecta a las Personas Introvertidas",
		//"Historias de Acoso en Jóvenes Introvertidos",
		//"El Efecto del Acoso en la Autoestima de Personas Introvertidas",
		//"Acoso en el Trabajo a Personas Introvertidas: Testimonios",
		//"Acoso en Redes Sociales y Personas Introvertidas",
		//"Cómo el Acoso Social Afecta a los Introvertidos",
		//"Casos de Acoso en Adolescentes Introvertidos",
		//"Testimonios de Acoso en Personas Introvertidas",
		//"Acoso en Espacios Públicos y la Vulnerabilidad de los Introvertidos",
		//"Relatos de Acoso en Universidades para Personas Introvertidas",
		//"Cómo el Acoso Afecta el Desarrollo Social de los Introvertidos",
		//"Acoso en Niños Introvertidos: Consecuencias a Largo Plazo",
		//"Acoso Laboral en Personas Introvertidas: Un Análisis",
		//"Relatos de Personas Introvertidas Víctimas de Acoso",
		//"Impacto del Acoso en la Salud Mental de los Introvertidos",
		//"Acoso en Redes Virtuales a Personas Introvertidas",
		//"Historias de Superación de Personas Introvertidas Víctimas de Acoso",
		//"Relatos de Acoso en el Colegio para Jóvenes Introvertidos",
		//"Acoso Emocional y Personas Introvertidas: Consecuencias Psicológicas",
		//"Personas Introvertidas y Acoso en Entornos Familiares",
		//"Acoso en Instituciones Educativas a Estudiantes Introvertidos",
		//"Cómo el Acoso Impacta las Relaciones Sociales de los Introvertidos",
		//"Relatos de Acoso en Espacios Recreativos y Personas Introvertidas",
		//"Acoso Escolar y el Aislamiento de las Personas Introvertidas",
		//"Impacto del Acoso Cibernético en Personas Introvertidas",
		//"Testimonios de Acoso Emocional en Personas Introvertidas",
		//"Cómo el Acoso Moldea la Personalidad de los Introvertidos",
		//"Acoso en el Transporte Público a Personas Introvertidas",
		//"Relatos de Acoso en Espacios Laborales para Personas Introvertidas",
		//"Personas Introvertidas y Acoso en la Adolescencia",
		//"El Efecto del Acoso en la Vida Social de los Introvertidos",
		//"Acoso en el Trabajo y la Timidez en los Introvertidos",
		//"Acoso en Adolescentes Introvertidos: Casos y Testimonios",
		//"Cómo el Acoso Aumenta la Ansiedad en los Introvertidos",
		//"Acoso en Espacios Públicos y la Ansiedad de los Introvertidos",
		//"Acoso Escolar y Aislamiento en Personas Introvertidas",
		//"Impacto del Acoso en las Relaciones Personales de los Introvertidos",
		//"Personas Introvertidas y el Acoso Social: Relatos Reales",
		//"Acoso en Universidades y el Silencio de los Introvertidos",
		//"Acoso en Facebook: Relatos Reales",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Redes Sociales",
		//"Acoso Cibernético en TikTok: Testimonios",
		//"Experiencias de Acoso en Facebook",
		//"Relatos de Acoso en Instagram",
		//"Acoso en TikTok: Historias Reales",
		//"Historias de Acoso en Grupos de Facebook",
		//"Acoso en Mensajes Privados: Relatos",
		//"Testimonios de Acoso en Redes Sociales",
		//"Acoso en Facebook Live: Relatos",
		//"Casos de Acoso en TikTok",
		//"Experiencias de Acoso en Comentarios de Facebook",
		//"Acoso en TikTok: Relatos de Víctimas",
		//"Acoso en Redes Sociales: Historias de Supervivencia",
		//"Historias de Acoso en Instagram Stories",
		//"Relatos de Acoso en TikTok en Vivo",
		//"Acoso en Facebook Messenger: Casos Reales",
		//"Acoso en TikTok y Su Impacto: Relatos",
		//"Relatos de Acoso en Comentarios de TikTok",
		//"Acoso en Grupos Privados de Facebook",
		//"Testimonios de Acoso en Directos de TikTok",
		//"Historias de Acoso en Redes Sociales",
		//"Acoso en Facebook: Relatos de Víctimas",
		//"Acoso en TikTok: Consecuencias Reales",
		//"Casos de Acoso en Facebook: Relatos",
		//"Relatos de Acoso en Videos de TikTok",
		//"Acoso en Facebook Marketplace: Testimonios",
		//"Experiencias de Acoso en TikTok",
		//"Relatos de Acoso en Redes como Facebook",
		//"Historias de Acoso en Redes: Facebook y TikTok",
		//"Acoso en Facebook y TikTok: Relatos Reales",
		//"Acoso Cibernético en Facebook: Testimonios",
		//"Relatos de Acoso en TikTok: Impacto Social",
		//"Acoso en Directos de Facebook",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Facebook: Experiencias",
		//"Acoso en TikTok y Facebook: Testimonios",
		//"Relatos de Acoso en Videos Virales de TikTok",
		//"Acoso en Redes: Historias de Facebook y TikTok",
		//"Acoso en WhatsApp: Relatos Reales",
		//"Historias de Acoso en YouTube",
		//"Relatos de Acoso en Snapchat",
		//"Acoso en Grupos de WhatsApp: Testimonios",
		//"Acoso en YouTube: Historias Reales",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Snapchat: Relatos de Víctimas",
		//"Testimonios de Acoso en YouTube",
		//"Acoso en Mensajes de WhatsApp",
		//"Acoso en Videos de YouTube: Historias",
		//"Relatos de Acoso en Snapchats Privados",
		//"Acoso en Grupos de WhatsApp: Casos Reales",
		//"Historias de Acoso en YouTube Live",
		//"Acoso en Snapchat: Experiencias Reales",
		//"Relatos de Acoso en WhatsApp Status",
		//"Acoso en YouTube: Relatos Impactantes",
		//"Relatos de Acoso en Mensajes de Snapchat",
		//"Acoso en Comentarios de YouTube: Testimonios",
		//"Experiencias de Acoso en WhatsApp",
		//"Relatos de Acoso en Videos de Snapchat",
		//"Acoso en Directos de YouTube: Historias",
		//"Relatos de Acoso en WhatsApp y Snapchat",
		//"Acoso en YouTube: Testimonios de Víctimas",
		//"Historias de Acoso en Grupos de WhatsApp",
		//"Acoso en Snapchats Públicos: Relatos Reales",
		//"Relatos de Acoso en YouTube Shorts",
		//"Acoso en WhatsApp: Testimonios Reales",
		//"Relatos de Acoso en Historias de Snapchat",
		//"Acoso en Videos de YouTube: Casos Documentados",
		//"Testimonios de Acoso en WhatsApp y Snapchat",
		//"Acoso en Grupos Privados de WhatsApp",
		//"Relatos de Acoso en YouTube y Snapchat",
		//"Acoso en Mensajes de WhatsApp: Historias",
		//"Historias de Acoso en YouTube y WhatsApp",
		//"Acoso en Snapchats y Videos de YouTube",
		//"Relatos de Acoso en Mensajes de WhatsApp",
		//"Acoso en YouTube y Snapchat: Testimonios",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Videos de YouTube y Snapchat",
		//"Acoso en WhatsApp y YouTube: Historias Reales",
		//"Historias de Acoso Escolar en Perú: Testimonios Reales",
		//"Acoso Laboral en Ecuador: Consecuencias Psicológicas",
		//"Relatos de Acoso en Redes Sociales en Venezuela",
		//"Testimonios de Acoso en Espacios Públicos en Chile",
		//"Acoso Cibernético en Colombia: Historias Impactantes",
		//"Historias de Acoso en Universidades de Argentina",
		//"Relatos de Acoso en el Transporte Público en Perú",
		//"Acoso Sexual en Espacios Laborales de Chile",
		//"Historias de Acoso Escolar en Venezuela",
		//"Acoso en Instituciones Educativas de Ecuador",
		//"Casos de Acoso en Redes Sociales en México",
		//"Acoso en Colegios de Perú: Testimonios de Víctimas",
		//"Historias de Acoso en el Transporte Público en Argentina",
		//"Acoso en Entornos Laborales en Colombia: Relatos Reales",
		//"Testimonios de Acoso en Plazas Públicas en Chile",
		//"Historias de Acoso en Centros Comerciales en Venezuela",
		//"Acoso en Universidades de Perú: Casos Documentados",
		//"Relatos de Acoso Sexual en Ecuador: Impacto Psicológico",
		//"Acoso en Redes Sociales en Argentina: Testimonios",
		//"Historias de Acoso en Escuelas de Chile: Un Análisis",
		//"Acoso Cibernético en México: Relatos de Víctimas",
		//"Testimonios de Acoso en Instituciones Educativas en Venezuela",
		//"Historias de Acoso en el Transporte Público en Ecuador",
		//"Acoso en Ambientes Laborales en Perú: Consecuencias Psicológicas",
		//"Acoso en Redes Sociales en Chile: Historias Reales",
		//"Relatos de Acoso en Colegios de Colombia",
		//"Historias de Acoso en el Ámbito Universitario en Argentina",
		//"Acoso en Instituciones de Salud en Venezuela",
		//"Testimonios de Acoso en el Trabajo en Ecuador",
		//"Historias de Acoso en la Calle en Perú",
		//"Relatos de Acoso Cibernético en Chile",
		//"Acoso Escolar en Colombia: Casos Documentados",
		//"Historias de Acoso en Redes Sociales en México",
		//"Acoso en Instituciones Públicas en Argentina",
		//"Testimonios de Acoso en el Transporte Público en Venezuela",
		//"Acoso en Espacios Laborales en Perú: Historias de Víctimas",
		//"Relatos de Acoso en Universidades de Chile",
		//"Historias de Acoso en el Ámbito Escolar en Ecuador",
		//"Acoso Sexual en Colombia: Testimonios y Consecuencias",
		//"Casos de Acoso en Redes Sociales en Venezuela",
		//"istorias de Acoso a Inmigrantes en Europa: Testimonios Reales",
		//"coso Laboral a Inmigrantes en Estados Unidos: Relatos de Víctimas",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público",
		//"coso en Redes Sociales a Inmigrantes: Casos Documentados",
		//"istorias de Acoso a Inmigrantes en Centros de Refugiados",
		//"coso Laboral a Inmigrantes en el Sector Agrícola",
		//"estimonios de Acoso a Inmigrantes en América Latina",
		//"elatos de Inmigrantes Víctimas de Acoso en el Trabajo",
		//"coso a Inmigrantes en Comunidades Virtuales: Historias Reales",
		//"istorias de Acoso a Inmigrantes en Países Europeos",
		//"coso en Universidades a Estudiantes Inmigrantes",
		//"elatos de Acoso a Inmigrantes en la Construcción",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público en Europa",
		//"coso en Escuelas a Hijos de Inmigrantes: Historias Reales",
		//"asos de Acoso a Inmigrantes en el Ámbito Sanitario",
		//"istorias de Inmigrantes Víctimas de Acoso en el Servicio Doméstico",
		//"elatos de Acoso en Centros de Detención de Inmigrantes",
		//"coso a Inmigrantes en Redes Sociales: Impacto Psicológico",
		//"istorias de Acoso a Inmigrantes en Países de Acogida",
		//"estimonios de Acoso a Inmigrantes en Zonas Fronterizas",
		//"elatos de Inmigrantes Víctimas de Acoso en Centros Educativos",
		//"coso en el Trabajo a Inmigrantes en Países Desarrollados",
		//"istorias de Acoso a Inmigrantes en Redes Sociales",
		//"estimonios de Acoso a Inmigrantes en el Ámbito Laboral",
		//"coso a Inmigrantes en el Transporte Público: Relatos Reales",
		//"istorias de Inmigrantes Víctimas de Acoso en América Latina",
		//"coso a Inmigrantes en Comunidades Online: Consecuencias Emocionales",
		//"elatos de Acoso en Lugares de Trabajo a Inmigrantes",
		//"estimonios de Acoso a Inmigrantes en Escuelas de Países de Acogida",
		//"coso a Inmigrantes en el Sector Servicios: Historias Reales",
		//"elatos de Inmigrantes Víctimas de Acoso en Países Europeos",
		//"istorias de Acoso a Inmigrantes en Entornos Laborales Hostiles",
		//"estimonios de Acoso a Inmigrantes en Espacios Públicos",
		//"coso a Inmigrantes en Países Desarrollados: Casos Documentados",
		//"elatos de Acoso a Inmigrantes en el Ámbito Escolar",
		//"istorias de Acoso a Inmigrantes en la Construcción y Agricultura",
		//"estimonios de Acoso a Inmigrantes en Oficinas Gubernamentales",
		//"coso a Inmigrantes en Entornos Urbanos: Relatos Impactantes",
		//"istorias de Inmigrantes Víctimas de Acoso en Redes Sociales",
		"estimonios de Acoso a Inmigrantes en Centros de Detención",
	}
	dsn := "root:secret@tcp(127.0.0.1:3309)/acosoDB"
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	// Verificar la conexión
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Conexión exitosa a la base de datos.")
	now := time.Now()
	for _, topic := range topics {
		//Insert into database
		id := uuid.New().String()
		projectId := "91da2ca7-6244-11ef-9d2f-0242ac110002"
		_, errEx := db.Exec(
			"INSERT INTO scraped_topics (id, project_id,title,created_at) VALUES (?,?,?,?)",
			id,
			projectId,
			topic,
			now,
		)

		if errEx != nil {
			fmt.Println("Error: ", errEx)
			panic(err)
		}

	}
	fmt.Println("Se han migrado los temas correctamente.")
}
