package main

import (
	"database/sql"
	"fmt"
	"github.com/google/uuid"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	topics := []string{
		//"Efectos Psicológicos del Acoso Escolar: Caminos hacia la Depresión",
		//"Impacto del Acoso Cibernético en la Salud Mental: Casos de Depresión",
		//"Depresión y Acoso en el Entorno Laboral: Testimonios Reales",
		//"Historias de Depresión por Acoso en Redes Sociales: Un Análisis Personal",
		//"Experiencias de Depresión en Víctimas de Acoso en Espacios Públicos",
		//"Relatos de Depresión y Acoso en Instituciones Educativas",
		//"El Ciclo de Acoso y Depresión: Cómo la Violencia Psicológica Afecta la Salud Mental",
		//"Testimonios de Depresión en Mujeres Adultas Tras Experiencias de Acoso",
		//"Acoso y Depresión en Jóvenes: Historias de Superación y Resiliencia",
		//"Cómo el Acoso Emocional Conduce a la Depresión: Experiencias en el Ámbito Familiar",
		//"Crónicas de Depresión en Víctimas de Acoso en el Trabajo: Un Enfoque Integral",
		//"Narrativas de Depresión y Bullying Escolar: Impacto a Largo Plazo",
		//"Historias de Depresión por Acoso en Espacios Recreativos: Efectos en la Autoestima",
		//"El Rol del Acoso en la Aparición de Trastornos Depresivos: Casos Documentados",
		//"Depresión Asociada al Acoso Sexual en Ambientes Académicos: Testimonios Personales",
		//"Foros de Víctimas de Acoso: Discusiones sobre la Relación con la Depresión",
		//"Relatos de Acoso en la Comunidad Virtual y su Impacto en la Salud Mental",
		//"Historias de Depresión en Adolescentes Víctimas de Acoso Escolar",
		//"Casos Reales de Depresión como Consecuencia de Acoso en Centros de Fitness",
		//"El Impacto del Acoso Psicológico en la Salud Mental: Historias de Depresión",
		//"Testimonios de Depresión Tras Experiencias de Acoso en Barrios",
		//"Narrativas de Depresión en Víctimas de Acoso en Colegios",
		//"Historias de Acoso en Espacios Laborales y sus Efectos Depresivos",
		//"Depresión y Acoso en Universidades: Testimonios de Estudiantes",
		//"Relatos de Depresión por Acoso en Centros Comerciales y Espacios Públicos",
		//"Casos de Depresión en Víctimas de Acoso en el Transporte Público",
		//"Crónicas de Depresión en Víctimas de Acoso Emocional en el Hogar",
		//"Experiencias de Depresión en Víctimas de Acoso en Plazas Públicas",
		//"Historias de Acoso Sexual y su Impacto en la Salud Mental: Casos de Depresión",
		//"El Efecto del Acoso en la Autoestima y su Relación con la Depresión",
		//"Narrativas de Depresión en Víctimas de Acoso en el Ámbito Deportivo",
		//"Historias de Acoso en Instituciones Educativas y su Relación con Trastornos Depresivos",
		//"Depresión y Acoso en la Comunidad: Casos y Testimonios",
		//"Foros sobre Acoso y Depresión: Testimonios de Víctimas",
		//"Relatos de Depresión en Víctimas de Acoso en Entornos Recreativos",
		//"Impacto del Acoso en la Salud Mental de Adultos Mayores: Historias de Depresión",
		//"Historias de Depresión por Acoso en la Red: Testimonios de Superación",
		//"Relatos de Depresión en Víctimas de Acoso en la Calle",
		//"Experiencias de Depresión en Víctimas de Acoso en Gimnasios y Centros de Fitness",
		//"El Rol del Acoso Psicológico en la Aparición de Trastornos Depresivos: Casos Reales",
		//"Impacto Psicológico de la Violación y el Acoso: Historias de Supervivencia",
		//"Experiencias de Violación y Acoso en Ambientes Educativos: Un Análisis Profundo",
		//"Testimonios de Violación y Acoso en el Trabajo: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso en Víctimas de Violación: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Violación y Acoso en la Comunidad Virtual: Impacto en la Salud Mental",
		//"Crónicas de Violación y Acoso en Instituciones Educativas: Efectos Psicológicos",
		//"Relatos de Violación y Acoso en Redes Sociales: Impacto en las Víctimas",
		//"Historias de Violación y Acoso en el Transporte Público: Testimonios de Víctimas",
		//"Casos Documentados de Violación y Acoso en Espacios Recreativos",
		//"El Rol del Acoso en Casos de Violación: Análisis de Efectos Psicológicos",
		//"Testimonios de Violación y Acoso en Barrios: Consecuencias a Largo Plazo",
		//"Violación y Acoso en Entornos Laborales: Impacto en la Salud Mental de los Empleados",
		//"Historias de Violación y Acoso en Instituciones de Educación Superior",
		//"Experiencias de Violación y Acoso en Ámbitos Deportivos: Testimonios Reales",
		//"El Impacto de la Violación y el Acoso en la Autoestima: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Plazas Públicas: Consecuencias Emocionales",
		//"Violación y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Historias de Violación y Acoso en Centros Comerciales: Casos y Reflexiones",
		//"Relatos de Violación y Acoso en Centros de Fitness: Impacto Psicológico en las Víctimas",
		//"Testimonios de Violación y Acoso en la Calle: Consecuencias para la Salud Mental",
		//"Violación y Acoso en Universidades: Un Estudio de Casos y Testimonios",
		//"El Efecto del Acoso Sexual en Casos de Violación: Experiencias y Consecuencias",
		//"Narrativas de Violación y Acoso en Espacios Laborales: Impacto en la Vida Profesional",
		//"Historias de Violación y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Casos Reales de Violación y Acoso en el Ámbito Educativo: Testimonios de Supervivientes",
		//"El Impacto del Acoso en Víctimas de Violación en el Ámbito Familiar",
		//"Experiencias de Violación y Acoso en Gimnasios: Consecuencias Emocionales",
		//"Historias de Violación y Acoso en Espacios Públicos: Un Análisis de Casos",
		//"Violación y Acoso en Foros de Víctimas: Discusiones sobre Impacto Psicológico",
		//"Relatos de Violación y Acoso en Espacios Recreativos: Impacto en la Salud Mental",
		//"Testimonios de Violación y Acoso en Instituciones de Salud: Consecuencias y Reflexiones",
		//"Historias de Violación y Acoso en Colegios: Un Estudio de Casos",
		//"El Efecto del Acoso Emocional en Casos de Violación: Testimonios de Víctimas",
		//"Violación y Acoso en el Transporte Público: Casos y Efectos Psicológicos",
		//"Narrativas de Violación y Acoso en el Ámbito Social: Consecuencias para las Víctimas",
		//"Historias de Violación y Acoso en Ámbitos Académicos: Impacto en la Salud Mental",
		//"Relatos de Violación y Acoso en Espacios Privados: Consecuencias Psicológicas",
		//"Experiencias de Violación y Acoso en Comunidades Virtuales: Un Enfoque Integral",
		//"El Impacto del Acoso en Casos de Violación: Consecuencias y Reflexiones",
		//"El Impacto del Acoso en el Desarrollo de la Bulimia: Testimonios de Víctimas",
		//"Relatos de Bulimia y Acoso en Instituciones Educativas: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Experiencias de Bulimia y Acoso en Redes Sociales: Consecuencias para la Salud Mental",
		//"Acoso Escolar y Bulimia: Un Análisis de Casos y Consecuencias",
		//"El Efecto del Acoso en la Bulimia: Testimonios de Supervivientes",
		//"Narrativas de Bulimia y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Bulimia y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Historias de Bulimia y Acoso en Comunidades Virtuales: Impacto Emocional",
		//"Testimonios de Bulimia y Acoso en el Transporte Público: Un Análisis",
		//"El Rol del Acoso en Casos de Bulimia: Consecuencias Psicológicas y Emocionales",
		//"Bulimia y Acoso en Espacios Recreativos: Casos y Reflexiones",
		//"Historias de Bulimia y Acoso en Entornos Educativos: Consecuencias para la Salud Mental",
		//"El Impacto del Acoso en el Desarrollo de Trastornos Alimentarios: Un Estudio de Bulimia",
		//"Relatos de Bulimia y Acoso en Instituciones de Salud: Consecuencias Emocionales",
		//"Acoso Cibernético y Bulimia: Consecuencias para la Salud Mental",
		//"Experiencias de Bulimia y Acoso en Entornos Deportivos: Testimonios Reales",
		//"Historias de Bulimia y Acoso en Centros Comerciales: Consecuencias Psicológicas",
		//"El Efecto del Acoso en la Autoestima y la Bulimia: Un Análisis de Casos",
		//"Relatos de Bulimia y Acoso en Espacios Laborales: Impacto Emocional",
		//"Historias de Bulimia y Acoso en Ámbitos Académicos: Consecuencias Psicológicas",
		//"El Impacto del Acoso Emocional en Casos de Bulimia: Testimonios de Víctimas",
		//"Bulimia y Acoso en Foros de Víctimas: Discusiones sobre Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Sociales: Consecuencias y Reflexiones",
		//"Experiencias de Bulimia y Acoso en la Calle: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en Centros de Fitness: Impacto Psicológico",
		//"Relatos de Bulimia y Acoso en la Comunidad Virtual: Un Enfoque Integral",
		//"Bulimia y Acoso en Espacios Privados: Consecuencias para la Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Académicos: Impacto en la Autoestima",
		//"Historias de Bulimia y Acoso en Blogs: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso Escolar en la Bulimia: Testimonios y Reflexiones",
		//"Relatos de Bulimia y Acoso en el Ámbito Familiar: Consecuencias Emocionales",
		//"Historias de Bulimia y Acoso en el Ámbito Social: Un Estudio de Casos",
		//"El Impacto del Acoso en el Comportamiento Alimentario: Casos de Bulimia",
		//"Testimonios de Bulimia y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Historias de Bulimia y Acoso en Espacios Educativos: Un Análisis de Casos",
		//"El Rol del Acoso en el Desarrollo de Trastornos Alimentarios: Un Enfoque en la Bulimia",
		//"Experiencias de Bulimia y Acoso en el Transporte Público: Consecuencias Psicológicas",
		//"Relatos de Bulimia y Acoso en Entornos Deportivos: Impacto Emocional en las Víctimas",
		//"Historias de Bulimia y Acoso en Instituciones Educativas: Impacto en la Autoestima",
		//"El Impacto del Acoso en Víctimas de Abandono Familiar: Historias de Superación",
		//"Relatos de Acoso y Abandono Familiar en Entornos Educativos: Un Análisis",
		//"Acoso en el Contexto del Abandono Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso y Abandono Familiar en Jóvenes: Un Camino hacia la Resiliencia",
		//"El Rol del Acoso en Víctimas de Abandono Familiar: Casos Documentados",
		//"Testimonios de Acoso y Abandono Familiar en Espacios Públicos",
		//"Historias de Abandono Familiar y Acoso en Redes Sociales: Impacto en la Salud Mental",
		//"Acoso en Niños y Adolescentes Víctimas de Abandono Familiar: Relatos Reales",
		//"Casos de Acoso en Víctimas de Abandono Familiar en el Ámbito Educativo",
		//"El Ciclo de Acoso y Abandono Familiar: Consecuencias Psicológicas a Largo Plazo",
		//"Relatos de Abandono Familiar y Acoso en Instituciones Educativas",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en la Adolescencia",
		//"El Impacto del Abandono Familiar y el Acoso en la Autoestima: Historias Reales",
		//"Acoso y Abandono Familiar en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Narrativas de Acoso y Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Niños: Consecuencias Emocionales",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Entornos Deportivos",
		//"Relatos de Acoso en Jóvenes Víctimas de Abandono Familiar: Impacto Psicológico",
		//"El Efecto del Acoso en Niños Víctimas de Abandono Familiar: Casos Documentados",
		//"Acoso en Víctimas de Abandono Familiar en Centros de Acogida: Historias Reales",
		//"Historias de Abandono Familiar y Acoso en la Vida Adulta: Testimonios de Superación",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Transporte Público",
		//"Acoso en Víctimas de Abandono Familiar en Centros Comerciales: Un Estudio de Casos",
		//"El Impacto del Abandono Familiar y el Acoso en la Salud Mental de las Víctimas",
		//"Casos de Acoso y Abandono Familiar en el Contexto Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso en Víctimas de Abandono Familiar en Instituciones de Salud",
		//"El Ciclo de Abandono Familiar y Acoso en Niños y Adolescentes: Testimonios Reales",
		//"Acoso en Víctimas de Abandono Familiar en Espacios Recreativos: Historias Reales",
		//"El Rol del Acoso en Víctimas de Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Efectos a Largo Plazo",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Colegios",
		//"Relatos de Acoso en Niños Víctimas de Abandono Familiar en Espacios Públicos",
		//"El Impacto del Acoso en Adolescentes Víctimas de Abandono Familiar: Historias Reales",
		//"Acoso y Abandono Familiar en Jóvenes Adultos: Consecuencias Psicológicas",
		//"Historias de Abandono Familiar y Acoso en el Ámbito Académico",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Ámbito Laboral",
		//"El Efecto del Abandono Familiar en el Desarrollo de Trastornos Psicológicos Relacionados con el Acoso",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Espacios Deportivos",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Consecuencias Emocionales",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en Espacios Recreativos",
		//"Acoso Escolar en Personas Introvertidas: Impacto Psicológico",
		//"Cómo el Acoso Afecta a las Personas Introvertidas",
		//"Historias de Acoso en Jóvenes Introvertidos",
		//"El Efecto del Acoso en la Autoestima de Personas Introvertidas",
		//"Acoso en el Trabajo a Personas Introvertidas: Testimonios",
		//"Acoso en Redes Sociales y Personas Introvertidas",
		//"Cómo el Acoso Social Afecta a los Introvertidos",
		//"Casos de Acoso en Adolescentes Introvertidos",
		//"Testimonios de Acoso en Personas Introvertidas",
		//"Acoso en Espacios Públicos y la Vulnerabilidad de los Introvertidos",
		//"Relatos de Acoso en Universidades para Personas Introvertidas",
		//"Cómo el Acoso Afecta el Desarrollo Social de los Introvertidos",
		//"Acoso en Niños Introvertidos: Consecuencias a Largo Plazo",
		//"Acoso Laboral en Personas Introvertidas: Un Análisis",
		//"Relatos de Personas Introvertidas Víctimas de Acoso",
		//"Impacto del Acoso en la Salud Mental de los Introvertidos",
		//"Acoso en Redes Virtuales a Personas Introvertidas",
		//"Historias de Superación de Personas Introvertidas Víctimas de Acoso",
		//"Relatos de Acoso en el Colegio para Jóvenes Introvertidos",
		//"Acoso Emocional y Personas Introvertidas: Consecuencias Psicológicas",
		//"Personas Introvertidas y Acoso en Entornos Familiares",
		//"Acoso en Instituciones Educativas a Estudiantes Introvertidos",
		//"Cómo el Acoso Impacta las Relaciones Sociales de los Introvertidos",
		//"Relatos de Acoso en Espacios Recreativos y Personas Introvertidas",
		//"Acoso Escolar y el Aislamiento de las Personas Introvertidas",
		//"Impacto del Acoso Cibernético en Personas Introvertidas",
		//"Testimonios de Acoso Emocional en Personas Introvertidas",
		//"Cómo el Acoso Moldea la Personalidad de los Introvertidos",
		//"Acoso en el Transporte Público a Personas Introvertidas",
		//"Relatos de Acoso en Espacios Laborales para Personas Introvertidas",
		//"Personas Introvertidas y Acoso en la Adolescencia",
		//"El Efecto del Acoso en la Vida Social de los Introvertidos",
		//"Acoso en el Trabajo y la Timidez en los Introvertidos",
		//"Acoso en Adolescentes Introvertidos: Casos y Testimonios",
		//"Cómo el Acoso Aumenta la Ansiedad en los Introvertidos",
		//"Acoso en Espacios Públicos y la Ansiedad de los Introvertidos",
		//"Acoso Escolar y Aislamiento en Personas Introvertidas",
		//"Impacto del Acoso en las Relaciones Personales de los Introvertidos",
		//"Personas Introvertidas y el Acoso Social: Relatos Reales",
		//"Acoso en Universidades y el Silencio de los Introvertidos",
		//"Acoso en Facebook: Relatos Reales",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Redes Sociales",
		//"Acoso Cibernético en TikTok: Testimonios",
		//"Experiencias de Acoso en Facebook",
		//"Relatos de Acoso en Instagram",
		//"Acoso en TikTok: Historias Reales",
		//"Historias de Acoso en Grupos de Facebook",
		//"Acoso en Mensajes Privados: Relatos",
		//"Testimonios de Acoso en Redes Sociales",
		//"Acoso en Facebook Live: Relatos",
		//"Casos de Acoso en TikTok",
		//"Experiencias de Acoso en Comentarios de Facebook",
		//"Acoso en TikTok: Relatos de Víctimas",
		//"Acoso en Redes Sociales: Historias de Supervivencia",
		//"Historias de Acoso en Instagram Stories",
		//"Relatos de Acoso en TikTok en Vivo",
		//"Acoso en Facebook Messenger: Casos Reales",
		//"Acoso en TikTok y Su Impacto: Relatos",
		//"Relatos de Acoso en Comentarios de TikTok",
		//"Acoso en Grupos Privados de Facebook",
		//"Testimonios de Acoso en Directos de TikTok",
		//"Historias de Acoso en Redes Sociales",
		//"Acoso en Facebook: Relatos de Víctimas",
		//"Acoso en TikTok: Consecuencias Reales",
		//"Casos de Acoso en Facebook: Relatos",
		//"Relatos de Acoso en Videos de TikTok",
		//"Acoso en Facebook Marketplace: Testimonios",
		//"Experiencias de Acoso en TikTok",
		//"Relatos de Acoso en Redes como Facebook",
		//"Historias de Acoso en Redes: Facebook y TikTok",
		//"Acoso en Facebook y TikTok: Relatos Reales",
		//"Acoso Cibernético en Facebook: Testimonios",
		//"Relatos de Acoso en TikTok: Impacto Social",
		//"Acoso en Directos de Facebook",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Facebook: Experiencias",
		//"Acoso en TikTok y Facebook: Testimonios",
		//"Relatos de Acoso en Videos Virales de TikTok",
		//"Acoso en Redes: Historias de Facebook y TikTok",
		//"Acoso en WhatsApp: Relatos Reales",
		//"Historias de Acoso en YouTube",
		//"Relatos de Acoso en Snapchat",
		//"Acoso en Grupos de WhatsApp: Testimonios",
		//"Acoso en YouTube: Historias Reales",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Snapchat: Relatos de Víctimas",
		//"Testimonios de Acoso en YouTube",
		//"Acoso en Mensajes de WhatsApp",
		//"Acoso en Videos de YouTube: Historias",
		//"Relatos de Acoso en Snapchats Privados",
		//"Acoso en Grupos de WhatsApp: Casos Reales",
		//"Historias de Acoso en YouTube Live",
		//"Acoso en Snapchat: Experiencias Reales",
		//"Relatos de Acoso en WhatsApp Status",
		//"Acoso en YouTube: Relatos Impactantes",
		//"Relatos de Acoso en Mensajes de Snapchat",
		//"Acoso en Comentarios de YouTube: Testimonios",
		//"Experiencias de Acoso en WhatsApp",
		//"Relatos de Acoso en Videos de Snapchat",
		//"Acoso en Directos de YouTube: Historias",
		//"Relatos de Acoso en WhatsApp y Snapchat",
		//"Acoso en YouTube: Testimonios de Víctimas",
		//"Historias de Acoso en Grupos de WhatsApp",
		//"Acoso en Snapchats Públicos: Relatos Reales",
		//"Relatos de Acoso en YouTube Shorts",
		//"Acoso en WhatsApp: Testimonios Reales",
		//"Relatos de Acoso en Historias de Snapchat",
		//"Acoso en Videos de YouTube: Casos Documentados",
		//"Testimonios de Acoso en WhatsApp y Snapchat",
		//"Acoso en Grupos Privados de WhatsApp",
		//"Relatos de Acoso en YouTube y Snapchat",
		//"Acoso en Mensajes de WhatsApp: Historias",
		//"Historias de Acoso en YouTube y WhatsApp",
		//"Acoso en Snapchats y Videos de YouTube",
		//"Relatos de Acoso en Mensajes de WhatsApp",
		//"Acoso en YouTube y Snapchat: Testimonios",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Videos de YouTube y Snapchat",
		//"Acoso en WhatsApp y YouTube: Historias Reales",
		//"Historias de Acoso Escolar en Perú: Testimonios Reales",
		//"Acoso Laboral en Ecuador: Consecuencias Psicológicas",
		//"Relatos de Acoso en Redes Sociales en Venezuela",
		//"Testimonios de Acoso en Espacios Públicos en Chile",
		//"Acoso Cibernético en Colombia: Historias Impactantes",
		//"Historias de Acoso en Universidades de Argentina",
		//"Relatos de Acoso en el Transporte Público en Perú",
		//"Acoso Sexual en Espacios Laborales de Chile",
		//"Historias de Acoso Escolar en Venezuela",
		//"Acoso en Instituciones Educativas de Ecuador",
		//"Casos de Acoso en Redes Sociales en México",
		//"Acoso en Colegios de Perú: Testimonios de Víctimas",
		//"Historias de Acoso en el Transporte Público en Argentina",
		//"Acoso en Entornos Laborales en Colombia: Relatos Reales",
		//"Testimonios de Acoso en Plazas Públicas en Chile",
		//"Historias de Acoso en Centros Comerciales en Venezuela",
		//"Acoso en Universidades de Perú: Casos Documentados",
		//"Relatos de Acoso Sexual en Ecuador: Impacto Psicológico",
		//"Acoso en Redes Sociales en Argentina: Testimonios",
		//"Historias de Acoso en Escuelas de Chile: Un Análisis",
		//"Acoso Cibernético en México: Relatos de Víctimas",
		//"Testimonios de Acoso en Instituciones Educativas en Venezuela",
		//"Historias de Acoso en el Transporte Público en Ecuador",
		//"Acoso en Ambientes Laborales en Perú: Consecuencias Psicológicas",
		//"Acoso en Redes Sociales en Chile: Historias Reales",
		//"Relatos de Acoso en Colegios de Colombia",
		//"Historias de Acoso en el Ámbito Universitario en Argentina",
		//"Acoso en Instituciones de Salud en Venezuela",
		//"Testimonios de Acoso en el Trabajo en Ecuador",
		//"Historias de Acoso en la Calle en Perú",
		//"Relatos de Acoso Cibernético en Chile",
		//"Acoso Escolar en Colombia: Casos Documentados",
		//"Historias de Acoso en Redes Sociales en México",
		//"Acoso en Instituciones Públicas en Argentina",
		//"Testimonios de Acoso en el Transporte Público en Venezuela",
		//"Acoso en Espacios Laborales en Perú: Historias de Víctimas",
		//"Relatos de Acoso en Universidades de Chile",
		//"Historias de Acoso en el Ámbito Escolar en Ecuador",
		//"Acoso Sexual en Colombia: Testimonios y Consecuencias",
		//"Casos de Acoso en Redes Sociales en Venezuela",
		//"istorias de Acoso a Inmigrantes en Europa: Testimonios Reales",
		//"coso Laboral a Inmigrantes en Estados Unidos: Relatos de Víctimas",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público",
		//"coso en Redes Sociales a Inmigrantes: Casos Documentados",
		//"istorias de Acoso a Inmigrantes en Centros de Refugiados",
		//"coso Laboral a Inmigrantes en el Sector Agrícola",
		//"estimonios de Acoso a Inmigrantes en América Latina",
		//"elatos de Inmigrantes Víctimas de Acoso en el Trabajo",
		//"coso a Inmigrantes en Comunidades Virtuales: Historias Reales",
		//"istorias de Acoso a Inmigrantes en Países Europeos",
		//"coso en Universidades a Estudiantes Inmigrantes",
		//"elatos de Acoso a Inmigrantes en la Construcción",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público en Europa",
		//"coso en Escuelas a Hijos de Inmigrantes: Historias Reales",
		//"asos de Acoso a Inmigrantes en el Ámbito Sanitario",
		//"istorias de Inmigrantes Víctimas de Acoso en el Servicio Doméstico",
		//"elatos de Acoso en Centros de Detención de Inmigrantes",
		//"coso a Inmigrantes en Redes Sociales: Impacto Psicológico",
		//"istorias de Acoso a Inmigrantes en Países de Acogida",
		//"estimonios de Acoso a Inmigrantes en Zonas Fronterizas",
		//"elatos de Inmigrantes Víctimas de Acoso en Centros Educativos",
		//"coso en el Trabajo a Inmigrantes en Países Desarrollados",
		//"istorias de Acoso a Inmigrantes en Redes Sociales",
		//"estimonios de Acoso a Inmigrantes en el Ámbito Laboral",
		//"coso a Inmigrantes en el Transporte Público: Relatos Reales",
		//"istorias de Inmigrantes Víctimas de Acoso en América Latina",
		//"coso a Inmigrantes en Comunidades Online: Consecuencias Emocionales",
		//"elatos de Acoso en Lugares de Trabajo a Inmigrantes",
		//"estimonios de Acoso a Inmigrantes en Escuelas de Países de Acogida",
		//"coso a Inmigrantes en el Sector Servicios: Historias Reales",
		//"elatos de Inmigrantes Víctimas de Acoso en Países Europeos",
		//"istorias de Acoso a Inmigrantes en Entornos Laborales Hostiles",
		//"estimonios de Acoso a Inmigrantes en Espacios Públicos",
		//"coso a Inmigrantes en Países Desarrollados: Casos Documentados",
		//"elatos de Acoso a Inmigrantes en el Ámbito Escolar",
		//"istorias de Acoso a Inmigrantes en la Construcción y Agricultura",
		//"estimonios de Acoso a Inmigrantes en Oficinas Gubernamentales",
		//"coso a Inmigrantes en Entornos Urbanos: Relatos Impactantes",
		//"istorias de Inmigrantes Víctimas de Acoso en Redes Sociales",
		//"estimonios de Acoso a Inmigrantes en Centros de Detención",
		"¿Qué es el acoso?",
		"Tipos de acoso",
		"Definición de acoso escolar",
		"Causas del acoso",
		"Efectos del acoso en la víctima",
		"Consecuencias legales del acoso",
		"Acoso físico vs acoso psicológico",
		"Cómo identificar el acoso",
		"Prevención del acoso",
		"Acoso cibernético o cyberbullying",
		"Acoso laboral: definición y ejemplos",
		"Señales de acoso en el trabajo",
		"Leyes contra el acoso laboral",
		"Diferencia entre acoso y bullying",
		"Acoso sexual: qué es y cómo prevenirlo",
		"Casos famosos de acoso sexual",
		"Acoso en redes sociales",
		"Cómo denunciar el acoso",
		"Protocolo ante situaciones de acoso",
		"Cómo actuar frente al acoso escolar",
		"Acoso escolar: guías para padres y maestros",
		"Acoso en adolescentes: causas y prevención",
		"Cómo afecta el acoso a la salud mental",
		"Víctimas de acoso: cómo brindar apoyo",
		"Estrategias para superar el acoso",
		"Perfiles de acosadores",
		"Acoso en línea: medidas de protección",
		"Impacto del acoso en el rendimiento escolar",
		"Acoso entre compañeros de trabajo",
		"Acoso escolar: estrategias de intervención",
		"Cyberbullying: casos y estudios",
		"Cómo evitar ser víctima de acoso en redes sociales",
		"El impacto del acoso en niños y adolescentes",
		"Acoso laboral: cómo afrontarlo legalmente",
		"Acoso en el ámbito académico",
		"Testimonios de víctimas de acoso",
		"Acoso y la influencia de la cultura digital",
		"Programas de concienciación sobre el acoso",
		"Dinámicas de poder en el acoso",
		"¿Cómo afecta el acoso a la autoestima?",
		"Psicología del acosador",
		"Tratamiento psicológico para víctimas de acoso",
		"Acoso y violencia de género",
		"Estrategias para evitar el acoso escolar",
		"Cómo el acoso afecta la vida adulta",
		"Cómo identificar un ambiente laboral tóxico",
		"Redes de apoyo para víctimas de acoso",
		"Impacto social del acoso en el entorno laboral",
		"Cómo el acoso afecta la productividad laboral",
		"Recursos para prevenir el acoso en instituciones educativas",
		"¿Qué es el ciberacoso?",
		"Tipos de ciberacoso",
		"Diferencias entre ciberacoso y bullying tradicional",
		"Consecuencias psicológicas del ciberacoso",
		"Cómo identificar el ciberacoso en redes sociales",
		"Ejemplos de ciberacoso en plataformas digitales",
		"Herramientas para prevenir el ciberacoso",
		"Cómo denunciar el ciberacoso",
		"Ciberacoso en adolescentes: casos y estadísticas",
		"Leyes contra el ciberacoso en diferentes países",
		"Estrategias para protegerse del ciberacoso",
		"Ciberacoso a través de mensajes de texto",
		"Señales de ciberacoso en menores de edad",
		"Cómo el ciberacoso afecta la salud mental",
		"Ciberacoso en foros y chats online",
		"Medidas de seguridad para evitar el ciberacoso",
		"Ciberacoso y anonimato en internet",
		"Cómo afecta el ciberacoso a la autoestima",
		"El impacto del ciberacoso en la sociedad",
		"Casos famosos de ciberacoso y sus consecuencias",
		"Efectos del ciberacoso a largo plazo",
		"Qué hacer si eres víctima de ciberacoso",
		"Prevención del ciberacoso en redes sociales",
		"Acoso en línea vs acoso presencial",
		"Perfil psicológico del ciberacosador",
		"Cómo proteger a los adolescentes del ciberacoso",
		"Impacto del ciberacoso en el rendimiento académico",
		"Consecuencias legales del ciberacoso en menores",
		"Ciberacoso y el papel de las plataformas sociales",
		"Estudios sobre la prevalencia del ciberacoso",
		"Ciberacoso a famosos: casos y análisis",
		"Campañas de concienciación sobre el ciberacoso",
		"Efectos del ciberacoso en la vida adulta",
		"Ciberacoso en aplicaciones de mensajería instantánea",
		"Cómo prevenir el ciberacoso en juegos online",
		"Testimonios de víctimas de ciberacoso",
		"Cómo las redes sociales responden al ciberacoso",
		"Estrategias legales para combatir el ciberacoso",
		"Factores de riesgo en el ciberacoso",
		"Métodos de ciberacoso más comunes",
		"Ciberacoso en plataformas de video y streaming",
		"Rol de los padres en la prevención del ciberacoso",
		"Ciberacoso entre compañeros de escuela",
		"Cómo afecta el ciberacoso la reputación online",
		"Ciberacoso y difamación: diferencias y semejanzas",
		"Herramientas tecnológicas para detectar ciberacoso",
		"Protocolos de actuación en casos de ciberacoso",
		"Cómo educar a los niños sobre el ciberacoso",
		"El papel de los influencers en la lucha contra el ciberacoso",
		"Consejos para evitar el ciberacoso en el entorno laboral",
		"Efectos a largo plazo del acoso en adultos",
		"Consecuencias del acoso en la salud física y emocional",
		"Técnicas psicológicas para tratar a víctimas de acoso",
		"Impacto del acoso en la identidad personal",
		"Estrategias legales para combatir el acoso",
		"Acoso entre compañeros de clase: estudios psicológicos",
		"Terapia cognitivo-conductual para víctimas de acoso",
		"Relación entre el acoso y el trastorno de estrés postraumático",
		"Acoso entre géneros: diferencias en víctimas y agresores",
		"Estudio de casos de acoso en el entorno educativo",
		"Rol de la tecnología en el aumento del acoso",
		"Comportamiento social en el acoso grupal",
		"Factores socioculturales que influyen en el acoso",
		"Perfiles psicológicos de acosadores en serie",
		"Acoso en la infancia y sus efectos en la adultez",
		"Rol del bystander en situaciones de acoso",
		"Cómo el acoso afecta el desarrollo cognitivo en niños",
		"Círculo vicioso del acoso: víctima convertida en acosador",
		"Acoso y exclusión social: estudios sociológicos",
		"Acoso sexual en el lugar de trabajo: estudios recientes",
		"Impacto del acoso en el bienestar psicológico de adolescentes",
		"Estrategias de afrontamiento para víctimas de acoso",
		"Rol de la empatía en la prevención del acoso",
		"Acoso en instituciones educativas: casos y políticas",
		"Estrategias de intervención ante el acoso en escuelas",
		"Efectos del acoso en la autoconfianza y la autoestima",
		"Modelos de intervención en acoso laboral",
		"Programas de rehabilitación para acosadores",
		"Métodos de mediación en casos de acoso escolar",
		"Papel de los padres en la prevención del acoso",
		"Causas psicológicas del acoso entre adolescentes",
		"Percepción social del acoso en el siglo XXI",
		"Acoso entre compañeros de trabajo: análisis de casos",
		"Impacto económico del acoso en el entorno laboral",
		"Cómo el acoso escolar afecta las habilidades sociales",
		"Técnicas de resolución de conflictos en casos de acoso",
		"Acoso y desigualdad de poder en las relaciones humanas",
		"Acoso en instituciones militares: análisis y prevención",
		"Factores de riesgo asociados al acoso escolar",
		"Cómo crear entornos laborales libres de acoso",
		"Estereotipos de género en el acoso sexual",
		"Legislación internacional sobre el acoso laboral",
		"Acoso entre hermanos: un problema no reconocido",
		"Técnicas de educación emocional para prevenir el acoso",
		"Impacto del acoso en la productividad laboral",
		"Cómo los medios de comunicación abordan el acoso",
		"Relación entre acoso y trastornos de ansiedad",
		"Acoso psicológico: diferencias con el acoso físico",
		"Programas de sensibilización sobre el acoso en jóvenes",
		"Evaluación del impacto del acoso en la dinámica familiar",
		"Cómo identificar un caso de ciberacoso",
		"Perfil del ciberacosador: análisis psicológico",
		"Consecuencias del ciberacoso en la salud mental",
		"Impacto del ciberacoso en la vida digital y personal",
		"Acoso en redes sociales: cómo detectarlo y prevenirlo",
		"Herramientas de monitoreo para ciberacoso en menores",
		"Relación entre ciberacoso y trastornos de ansiedad",
		"Ciberacoso en adolescentes: estrategias de prevención",
		"Casos de ciberacoso en escuelas: análisis de casos reales",
		"Cómo el ciberacoso afecta la identidad digital",
		"Ciberacoso en grupos de WhatsApp y aplicaciones de mensajería",
		"Rol del anonimato en el aumento del ciberacoso",
		"Diferencias entre ciberacoso y trolling",
		"Impacto del ciberacoso en la autoestima de los adolescentes",
		"Estrategias legales para combatir el ciberacoso",
		"Cómo se utiliza la tecnología para llevar a cabo el ciberacoso",
		"Ciberacoso en plataformas de video como YouTube y TikTok",
		"Efectos del ciberacoso en la reputación online",
		"El papel de las plataformas sociales en el ciberacoso",
		"Prevención del ciberacoso en aplicaciones móviles",
		"Acoso digital y leyes de protección de datos",
		"Ciberacoso en el ámbito laboral: casos y estrategias",
		"Cómo afecta el ciberacoso al rendimiento académico",
		"El impacto del ciberacoso en la vida adulta",
		"Ciberacoso en el gaming: acoso en comunidades de videojuegos",
		"Análisis de casos judiciales sobre ciberacoso",
		"Ciberacoso en menores: cómo proteger a los niños online",
		"Métodos de intervención en casos de ciberacoso",
		"El papel de los padres en la prevención del ciberacoso",
		"Herramientas tecnológicas para denunciar el ciberacoso",
		"Impacto emocional del ciberacoso en jóvenes",
		"Señales de ciberacoso en el entorno escolar",
		"Ciberacoso en influencers y creadores de contenido",
		"Relación entre el ciberacoso y el sexting",
		"Herramientas de seguridad para protegerse del ciberacoso",
		"Psicología del ciberacosador: motivaciones y conductas",
		"Cómo el ciberacoso afecta la privacidad online",
		"Estrategias de redes sociales para combatir el ciberacoso",
		"Casos de ciberacoso en famosos: consecuencias legales",
		"Diferencias entre ciberacoso y acoso tradicional",
		"Programas educativos para prevenir el ciberacoso",
		"Técnicas de detección de ciberacoso en entornos virtuales",
		"Impacto del ciberacoso en la identidad de género",
		"Rol de las instituciones educativas en la prevención del ciberacoso",
		"El papel de la inteligencia artificial en la lucha contra el ciberacoso",
		"Dinámicas grupales en el ciberacoso: cómo se propaga en redes",
		"Prevención del ciberacoso en entornos corporativos",
		"Estudios recientes sobre la prevalencia del ciberacoso",
		"Recursos para víctimas de ciberacoso",
		"Acoso en el metaverso: nuevos desafíos del ciberacoso",
	}
	dsn := "root:secret@tcp(127.0.0.1:3309)/acosoDB"
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	// Verificar la conexión
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Conexión exitosa a la base de datos.")
	now := time.Now()
	for _, topic := range topics {
		//Insert into database
		id := uuid.New().String()
		projectId := "91da2ca7-6244-11ef-9d2f-0242ac110002"
		_, errEx := db.Exec(
			"INSERT INTO scraped_topics (id, project_id,title,created_at) VALUES (?,?,?,?)",
			id,
			projectId,
			topic,
			now,
		)

		if errEx != nil {
			fmt.Println("Error: ", errEx)
			panic(err)
		}

	}
	fmt.Println("Se han migrado los temas correctamente.")
}
