package main

import (
	"database/sql"
	"fmt"
	"github.com/google/uuid"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	topics := []string{
		//"Efectos Psicológicos del Acoso Escolar: Caminos hacia la Depresión",
		//"Impacto del Acoso Cibernético en la Salud Mental: Casos de Depresión",
		//"Depresión y Acoso en el Entorno Laboral: Testimonios Reales",
		//"Historias de Depresión por Acoso en Redes Sociales: Un Análisis Personal",
		//"Experiencias de Depresión en Víctimas de Acoso en Espacios Públicos",
		//"Relatos de Depresión y Acoso en Instituciones Educativas",
		//"El Ciclo de Acoso y Depresión: Cómo la Violencia Psicológica Afecta la Salud Mental",
		//"Testimonios de Depresión en Mujeres Adultas Tras Experiencias de Acoso",
		//"Acoso y Depresión en Jóvenes: Historias de Superación y Resiliencia",
		//"Cómo el Acoso Emocional Conduce a la Depresión: Experiencias en el Ámbito Familiar",
		//"Crónicas de Depresión en Víctimas de Acoso en el Trabajo: Un Enfoque Integral",
		//"Narrativas de Depresión y Bullying Escolar: Impacto a Largo Plazo",
		//"Historias de Depresión por Acoso en Espacios Recreativos: Efectos en la Autoestima",
		//"El Rol del Acoso en la Aparición de Trastornos Depresivos: Casos Documentados",
		//"Depresión Asociada al Acoso Sexual en Ambientes Académicos: Testimonios Personales",
		//"Foros de Víctimas de Acoso: Discusiones sobre la Relación con la Depresión",
		//"Relatos de Acoso en la Comunidad Virtual y su Impacto en la Salud Mental",
		//"Historias de Depresión en Adolescentes Víctimas de Acoso Escolar",
		//"Casos Reales de Depresión como Consecuencia de Acoso en Centros de Fitness",
		//"El Impacto del Acoso Psicológico en la Salud Mental: Historias de Depresión",
		//"Testimonios de Depresión Tras Experiencias de Acoso en Barrios",
		//"Narrativas de Depresión en Víctimas de Acoso en Colegios",
		//"Historias de Acoso en Espacios Laborales y sus Efectos Depresivos",
		//"Depresión y Acoso en Universidades: Testimonios de Estudiantes",
		//"Relatos de Depresión por Acoso en Centros Comerciales y Espacios Públicos",
		//"Casos de Depresión en Víctimas de Acoso en el Transporte Público",
		//"Crónicas de Depresión en Víctimas de Acoso Emocional en el Hogar",
		//"Experiencias de Depresión en Víctimas de Acoso en Plazas Públicas",
		//"Historias de Acoso Sexual y su Impacto en la Salud Mental: Casos de Depresión",
		//"El Efecto del Acoso en la Autoestima y su Relación con la Depresión",
		//"Narrativas de Depresión en Víctimas de Acoso en el Ámbito Deportivo",
		//"Historias de Acoso en Instituciones Educativas y su Relación con Trastornos Depresivos",
		//"Depresión y Acoso en la Comunidad: Casos y Testimonios",
		//"Foros sobre Acoso y Depresión: Testimonios de Víctimas",
		//"Relatos de Depresión en Víctimas de Acoso en Entornos Recreativos",
		//"Impacto del Acoso en la Salud Mental de Adultos Mayores: Historias de Depresión",
		//"Historias de Depresión por Acoso en la Red: Testimonios de Superación",
		//"Relatos de Depresión en Víctimas de Acoso en la Calle",
		//"Experiencias de Depresión en Víctimas de Acoso en Gimnasios y Centros de Fitness",
		//"El Rol del Acoso Psicológico en la Aparición de Trastornos Depresivos: Casos Reales",
		//"Impacto Psicológico de la Violación y el Acoso: Historias de Supervivencia",
		//"Experiencias de Violación y Acoso en Ambientes Educativos: Un Análisis Profundo",
		//"Testimonios de Violación y Acoso en el Trabajo: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso en Víctimas de Violación: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Violación y Acoso en la Comunidad Virtual: Impacto en la Salud Mental",
		//"Crónicas de Violación y Acoso en Instituciones Educativas: Efectos Psicológicos",
		//"Relatos de Violación y Acoso en Redes Sociales: Impacto en las Víctimas",
		//"Historias de Violación y Acoso en el Transporte Público: Testimonios de Víctimas",
		//"Casos Documentados de Violación y Acoso en Espacios Recreativos",
		//"El Rol del Acoso en Casos de Violación: Análisis de Efectos Psicológicos",
		//"Testimonios de Violación y Acoso en Barrios: Consecuencias a Largo Plazo",
		//"Violación y Acoso en Entornos Laborales: Impacto en la Salud Mental de los Empleados",
		//"Historias de Violación y Acoso en Instituciones de Educación Superior",
		//"Experiencias de Violación y Acoso en Ámbitos Deportivos: Testimonios Reales",
		//"El Impacto de la Violación y el Acoso en la Autoestima: Casos y Testimonios",
		//"Narrativas de Violación y Acoso en Plazas Públicas: Consecuencias Emocionales",
		//"Violación y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Historias de Violación y Acoso en Centros Comerciales: Casos y Reflexiones",
		//"Relatos de Violación y Acoso en Centros de Fitness: Impacto Psicológico en las Víctimas",
		//"Testimonios de Violación y Acoso en la Calle: Consecuencias para la Salud Mental",
		//"Violación y Acoso en Universidades: Un Estudio de Casos y Testimonios",
		//"El Efecto del Acoso Sexual en Casos de Violación: Experiencias y Consecuencias",
		//"Narrativas de Violación y Acoso en Espacios Laborales: Impacto en la Vida Profesional",
		//"Historias de Violación y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Casos Reales de Violación y Acoso en el Ámbito Educativo: Testimonios de Supervivientes",
		//"El Impacto del Acoso en Víctimas de Violación en el Ámbito Familiar",
		//"Experiencias de Violación y Acoso en Gimnasios: Consecuencias Emocionales",
		//"Historias de Violación y Acoso en Espacios Públicos: Un Análisis de Casos",
		//"Violación y Acoso en Foros de Víctimas: Discusiones sobre Impacto Psicológico",
		//"Relatos de Violación y Acoso en Espacios Recreativos: Impacto en la Salud Mental",
		//"Testimonios de Violación y Acoso en Instituciones de Salud: Consecuencias y Reflexiones",
		//"Historias de Violación y Acoso en Colegios: Un Estudio de Casos",
		//"El Efecto del Acoso Emocional en Casos de Violación: Testimonios de Víctimas",
		//"Violación y Acoso en el Transporte Público: Casos y Efectos Psicológicos",
		//"Narrativas de Violación y Acoso en el Ámbito Social: Consecuencias para las Víctimas",
		//"Historias de Violación y Acoso en Ámbitos Académicos: Impacto en la Salud Mental",
		//"Relatos de Violación y Acoso en Espacios Privados: Consecuencias Psicológicas",
		//"Experiencias de Violación y Acoso en Comunidades Virtuales: Un Enfoque Integral",
		//"El Impacto del Acoso en Casos de Violación: Consecuencias y Reflexiones",
		//"El Impacto del Acoso en el Desarrollo de la Bulimia: Testimonios de Víctimas",
		//"Relatos de Bulimia y Acoso en Instituciones Educativas: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Experiencias de Bulimia y Acoso en Redes Sociales: Consecuencias para la Salud Mental",
		//"Acoso Escolar y Bulimia: Un Análisis de Casos y Consecuencias",
		//"El Efecto del Acoso en la Bulimia: Testimonios de Supervivientes",
		//"Narrativas de Bulimia y Acoso en el Ámbito Familiar: Impacto en la Salud Mental",
		//"Bulimia y Acoso en Espacios Públicos: Un Enfoque Integral",
		//"Historias de Bulimia y Acoso en Comunidades Virtuales: Impacto Emocional",
		//"Testimonios de Bulimia y Acoso en el Transporte Público: Un Análisis",
		//"El Rol del Acoso en Casos de Bulimia: Consecuencias Psicológicas y Emocionales",
		//"Bulimia y Acoso en Espacios Recreativos: Casos y Reflexiones",
		//"Historias de Bulimia y Acoso en Entornos Educativos: Consecuencias para la Salud Mental",
		//"El Impacto del Acoso en el Desarrollo de Trastornos Alimentarios: Un Estudio de Bulimia",
		//"Relatos de Bulimia y Acoso en Instituciones de Salud: Consecuencias Emocionales",
		//"Acoso Cibernético y Bulimia: Consecuencias para la Salud Mental",
		//"Experiencias de Bulimia y Acoso en Entornos Deportivos: Testimonios Reales",
		//"Historias de Bulimia y Acoso en Centros Comerciales: Consecuencias Psicológicas",
		//"El Efecto del Acoso en la Autoestima y la Bulimia: Un Análisis de Casos",
		//"Relatos de Bulimia y Acoso en Espacios Laborales: Impacto Emocional",
		//"Historias de Bulimia y Acoso en Ámbitos Académicos: Consecuencias Psicológicas",
		//"El Impacto del Acoso Emocional en Casos de Bulimia: Testimonios de Víctimas",
		//"Bulimia y Acoso en Foros de Víctimas: Discusiones sobre Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Sociales: Consecuencias y Reflexiones",
		//"Experiencias de Bulimia y Acoso en la Calle: Un Estudio de Casos",
		//"Historias de Bulimia y Acoso en Centros de Fitness: Impacto Psicológico",
		//"Relatos de Bulimia y Acoso en la Comunidad Virtual: Un Enfoque Integral",
		//"Bulimia y Acoso en Espacios Privados: Consecuencias para la Salud Mental",
		//"Testimonios de Bulimia y Acoso en Ámbitos Académicos: Impacto en la Autoestima",
		//"Historias de Bulimia y Acoso en Blogs: Consecuencias para la Salud Mental",
		//"El Efecto del Acoso Escolar en la Bulimia: Testimonios y Reflexiones",
		//"Relatos de Bulimia y Acoso en el Ámbito Familiar: Consecuencias Emocionales",
		//"Historias de Bulimia y Acoso en el Ámbito Social: Un Estudio de Casos",
		//"El Impacto del Acoso en el Comportamiento Alimentario: Casos de Bulimia",
		//"Testimonios de Bulimia y Acoso en Comunidades Virtuales: Consecuencias Psicológicas",
		//"Historias de Bulimia y Acoso en Espacios Educativos: Un Análisis de Casos",
		//"El Rol del Acoso en el Desarrollo de Trastornos Alimentarios: Un Enfoque en la Bulimia",
		//"Experiencias de Bulimia y Acoso en el Transporte Público: Consecuencias Psicológicas",
		//"Relatos de Bulimia y Acoso en Entornos Deportivos: Impacto Emocional en las Víctimas",
		//"Historias de Bulimia y Acoso en Instituciones Educativas: Impacto en la Autoestima",
		//"El Impacto del Acoso en Víctimas de Abandono Familiar: Historias de Superación",
		//"Relatos de Acoso y Abandono Familiar en Entornos Educativos: Un Análisis",
		//"Acoso en el Contexto del Abandono Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso y Abandono Familiar en Jóvenes: Un Camino hacia la Resiliencia",
		//"El Rol del Acoso en Víctimas de Abandono Familiar: Casos Documentados",
		//"Testimonios de Acoso y Abandono Familiar en Espacios Públicos",
		//"Historias de Abandono Familiar y Acoso en Redes Sociales: Impacto en la Salud Mental",
		//"Acoso en Niños y Adolescentes Víctimas de Abandono Familiar: Relatos Reales",
		//"Casos de Acoso en Víctimas de Abandono Familiar en el Ámbito Educativo",
		//"El Ciclo de Acoso y Abandono Familiar: Consecuencias Psicológicas a Largo Plazo",
		//"Relatos de Abandono Familiar y Acoso en Instituciones Educativas",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en la Adolescencia",
		//"El Impacto del Abandono Familiar y el Acoso en la Autoestima: Historias Reales",
		//"Acoso y Abandono Familiar en el Ámbito Laboral: Consecuencias Psicológicas",
		//"Narrativas de Acoso y Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Niños: Consecuencias Emocionales",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Entornos Deportivos",
		//"Relatos de Acoso en Jóvenes Víctimas de Abandono Familiar: Impacto Psicológico",
		//"El Efecto del Acoso en Niños Víctimas de Abandono Familiar: Casos Documentados",
		//"Acoso en Víctimas de Abandono Familiar en Centros de Acogida: Historias Reales",
		//"Historias de Abandono Familiar y Acoso en la Vida Adulta: Testimonios de Superación",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Transporte Público",
		//"Acoso en Víctimas de Abandono Familiar en Centros Comerciales: Un Estudio de Casos",
		//"El Impacto del Abandono Familiar y el Acoso en la Salud Mental de las Víctimas",
		//"Casos de Acoso y Abandono Familiar en el Contexto Familiar: Consecuencias Psicológicas",
		//"Historias de Acoso en Víctimas de Abandono Familiar en Instituciones de Salud",
		//"El Ciclo de Abandono Familiar y Acoso en Niños y Adolescentes: Testimonios Reales",
		//"Acoso en Víctimas de Abandono Familiar en Espacios Recreativos: Historias Reales",
		//"El Rol del Acoso en Víctimas de Abandono Familiar en Comunidades Virtuales",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Efectos a Largo Plazo",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Colegios",
		//"Relatos de Acoso en Niños Víctimas de Abandono Familiar en Espacios Públicos",
		//"El Impacto del Acoso en Adolescentes Víctimas de Abandono Familiar: Historias Reales",
		//"Acoso y Abandono Familiar en Jóvenes Adultos: Consecuencias Psicológicas",
		//"Historias de Abandono Familiar y Acoso en el Ámbito Académico",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en el Ámbito Laboral",
		//"El Efecto del Abandono Familiar en el Desarrollo de Trastornos Psicológicos Relacionados con el Acoso",
		//"Testimonios de Acoso en Víctimas de Abandono Familiar en Espacios Deportivos",
		//"Historias de Abandono Familiar y Acoso en Adolescentes: Consecuencias Emocionales",
		//"Relatos de Acoso en Víctimas de Abandono Familiar en Espacios Recreativos",
		//"Acoso Escolar en Personas Introvertidas: Impacto Psicológico",
		//"Cómo el Acoso Afecta a las Personas Introvertidas",
		//"Historias de Acoso en Jóvenes Introvertidos",
		//"El Efecto del Acoso en la Autoestima de Personas Introvertidas",
		//"Acoso en el Trabajo a Personas Introvertidas: Testimonios",
		//"Acoso en Redes Sociales y Personas Introvertidas",
		//"Cómo el Acoso Social Afecta a los Introvertidos",
		//"Casos de Acoso en Adolescentes Introvertidos",
		//"Testimonios de Acoso en Personas Introvertidas",
		//"Acoso en Espacios Públicos y la Vulnerabilidad de los Introvertidos",
		//"Relatos de Acoso en Universidades para Personas Introvertidas",
		//"Cómo el Acoso Afecta el Desarrollo Social de los Introvertidos",
		//"Acoso en Niños Introvertidos: Consecuencias a Largo Plazo",
		//"Acoso Laboral en Personas Introvertidas: Un Análisis",
		//"Relatos de Personas Introvertidas Víctimas de Acoso",
		//"Impacto del Acoso en la Salud Mental de los Introvertidos",
		//"Acoso en Redes Virtuales a Personas Introvertidas",
		//"Historias de Superación de Personas Introvertidas Víctimas de Acoso",
		//"Relatos de Acoso en el Colegio para Jóvenes Introvertidos",
		//"Acoso Emocional y Personas Introvertidas: Consecuencias Psicológicas",
		//"Personas Introvertidas y Acoso en Entornos Familiares",
		//"Acoso en Instituciones Educativas a Estudiantes Introvertidos",
		//"Cómo el Acoso Impacta las Relaciones Sociales de los Introvertidos",
		//"Relatos de Acoso en Espacios Recreativos y Personas Introvertidas",
		//"Acoso Escolar y el Aislamiento de las Personas Introvertidas",
		//"Impacto del Acoso Cibernético en Personas Introvertidas",
		//"Testimonios de Acoso Emocional en Personas Introvertidas",
		//"Cómo el Acoso Moldea la Personalidad de los Introvertidos",
		//"Acoso en el Transporte Público a Personas Introvertidas",
		//"Relatos de Acoso en Espacios Laborales para Personas Introvertidas",
		//"Personas Introvertidas y Acoso en la Adolescencia",
		//"El Efecto del Acoso en la Vida Social de los Introvertidos",
		//"Acoso en el Trabajo y la Timidez en los Introvertidos",
		//"Acoso en Adolescentes Introvertidos: Casos y Testimonios",
		//"Cómo el Acoso Aumenta la Ansiedad en los Introvertidos",
		//"Acoso en Espacios Públicos y la Ansiedad de los Introvertidos",
		//"Acoso Escolar y Aislamiento en Personas Introvertidas",
		//"Impacto del Acoso en las Relaciones Personales de los Introvertidos",
		//"Personas Introvertidas y el Acoso Social: Relatos Reales",
		//"Acoso en Universidades y el Silencio de los Introvertidos",
		//"Acoso en Facebook: Relatos Reales",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Redes Sociales",
		//"Acoso Cibernético en TikTok: Testimonios",
		//"Experiencias de Acoso en Facebook",
		//"Relatos de Acoso en Instagram",
		//"Acoso en TikTok: Historias Reales",
		//"Historias de Acoso en Grupos de Facebook",
		//"Acoso en Mensajes Privados: Relatos",
		//"Testimonios de Acoso en Redes Sociales",
		//"Acoso en Facebook Live: Relatos",
		//"Casos de Acoso en TikTok",
		//"Experiencias de Acoso en Comentarios de Facebook",
		//"Acoso en TikTok: Relatos de Víctimas",
		//"Acoso en Redes Sociales: Historias de Supervivencia",
		//"Historias de Acoso en Instagram Stories",
		//"Relatos de Acoso en TikTok en Vivo",
		//"Acoso en Facebook Messenger: Casos Reales",
		//"Acoso en TikTok y Su Impacto: Relatos",
		//"Relatos de Acoso en Comentarios de TikTok",
		//"Acoso en Grupos Privados de Facebook",
		//"Testimonios de Acoso en Directos de TikTok",
		//"Historias de Acoso en Redes Sociales",
		//"Acoso en Facebook: Relatos de Víctimas",
		//"Acoso en TikTok: Consecuencias Reales",
		//"Casos de Acoso en Facebook: Relatos",
		//"Relatos de Acoso en Videos de TikTok",
		//"Acoso en Facebook Marketplace: Testimonios",
		//"Experiencias de Acoso en TikTok",
		//"Relatos de Acoso en Redes como Facebook",
		//"Historias de Acoso en Redes: Facebook y TikTok",
		//"Acoso en Facebook y TikTok: Relatos Reales",
		//"Acoso Cibernético en Facebook: Testimonios",
		//"Relatos de Acoso en TikTok: Impacto Social",
		//"Acoso en Directos de Facebook",
		//"Historias de Acoso en TikTok",
		//"Relatos de Acoso en Facebook: Experiencias",
		//"Acoso en TikTok y Facebook: Testimonios",
		//"Relatos de Acoso en Videos Virales de TikTok",
		//"Acoso en Redes: Historias de Facebook y TikTok",
		//"Acoso en WhatsApp: Relatos Reales",
		//"Historias de Acoso en YouTube",
		//"Relatos de Acoso en Snapchat",
		//"Acoso en Grupos de WhatsApp: Testimonios",
		//"Acoso en YouTube: Historias Reales",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Snapchat: Relatos de Víctimas",
		//"Testimonios de Acoso en YouTube",
		//"Acoso en Mensajes de WhatsApp",
		//"Acoso en Videos de YouTube: Historias",
		//"Relatos de Acoso en Snapchats Privados",
		//"Acoso en Grupos de WhatsApp: Casos Reales",
		//"Historias de Acoso en YouTube Live",
		//"Acoso en Snapchat: Experiencias Reales",
		//"Relatos de Acoso en WhatsApp Status",
		//"Acoso en YouTube: Relatos Impactantes",
		//"Relatos de Acoso en Mensajes de Snapchat",
		//"Acoso en Comentarios de YouTube: Testimonios",
		//"Experiencias de Acoso en WhatsApp",
		//"Relatos de Acoso en Videos de Snapchat",
		//"Acoso en Directos de YouTube: Historias",
		//"Relatos de Acoso en WhatsApp y Snapchat",
		//"Acoso en YouTube: Testimonios de Víctimas",
		//"Historias de Acoso en Grupos de WhatsApp",
		//"Acoso en Snapchats Públicos: Relatos Reales",
		//"Relatos de Acoso en YouTube Shorts",
		//"Acoso en WhatsApp: Testimonios Reales",
		//"Relatos de Acoso en Historias de Snapchat",
		//"Acoso en Videos de YouTube: Casos Documentados",
		//"Testimonios de Acoso en WhatsApp y Snapchat",
		//"Acoso en Grupos Privados de WhatsApp",
		//"Relatos de Acoso en YouTube y Snapchat",
		//"Acoso en Mensajes de WhatsApp: Historias",
		//"Historias de Acoso en YouTube y WhatsApp",
		//"Acoso en Snapchats y Videos de YouTube",
		//"Relatos de Acoso en Mensajes de WhatsApp",
		//"Acoso en YouTube y Snapchat: Testimonios",
		//"Relatos de Acoso en Chats de WhatsApp",
		//"Acoso en Videos de YouTube y Snapchat",
		//"Acoso en WhatsApp y YouTube: Historias Reales",
		//"Historias de Acoso Escolar en Perú: Testimonios Reales",
		//"Acoso Laboral en Ecuador: Consecuencias Psicológicas",
		//"Relatos de Acoso en Redes Sociales en Venezuela",
		//"Testimonios de Acoso en Espacios Públicos en Chile",
		//"Acoso Cibernético en Colombia: Historias Impactantes",
		//"Historias de Acoso en Universidades de Argentina",
		//"Relatos de Acoso en el Transporte Público en Perú",
		//"Acoso Sexual en Espacios Laborales de Chile",
		//"Historias de Acoso Escolar en Venezuela",
		//"Acoso en Instituciones Educativas de Ecuador",
		//"Casos de Acoso en Redes Sociales en México",
		//"Acoso en Colegios de Perú: Testimonios de Víctimas",
		//"Historias de Acoso en el Transporte Público en Argentina",
		//"Acoso en Entornos Laborales en Colombia: Relatos Reales",
		//"Testimonios de Acoso en Plazas Públicas en Chile",
		//"Historias de Acoso en Centros Comerciales en Venezuela",
		//"Acoso en Universidades de Perú: Casos Documentados",
		//"Relatos de Acoso Sexual en Ecuador: Impacto Psicológico",
		//"Acoso en Redes Sociales en Argentina: Testimonios",
		//"Historias de Acoso en Escuelas de Chile: Un Análisis",
		//"Acoso Cibernético en México: Relatos de Víctimas",
		//"Testimonios de Acoso en Instituciones Educativas en Venezuela",
		//"Historias de Acoso en el Transporte Público en Ecuador",
		//"Acoso en Ambientes Laborales en Perú: Consecuencias Psicológicas",
		//"Acoso en Redes Sociales en Chile: Historias Reales",
		//"Relatos de Acoso en Colegios de Colombia",
		//"Historias de Acoso en el Ámbito Universitario en Argentina",
		//"Acoso en Instituciones de Salud en Venezuela",
		//"Testimonios de Acoso en el Trabajo en Ecuador",
		//"Historias de Acoso en la Calle en Perú",
		//"Relatos de Acoso Cibernético en Chile",
		//"Acoso Escolar en Colombia: Casos Documentados",
		//"Historias de Acoso en Redes Sociales en México",
		//"Acoso en Instituciones Públicas en Argentina",
		//"Testimonios de Acoso en el Transporte Público en Venezuela",
		//"Acoso en Espacios Laborales en Perú: Historias de Víctimas",
		//"Relatos de Acoso en Universidades de Chile",
		//"Historias de Acoso en el Ámbito Escolar en Ecuador",
		//"Acoso Sexual en Colombia: Testimonios y Consecuencias",
		//"Casos de Acoso en Redes Sociales en Venezuela",
		//"istorias de Acoso a Inmigrantes en Europa: Testimonios Reales",
		//"coso Laboral a Inmigrantes en Estados Unidos: Relatos de Víctimas",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público",
		//"coso en Redes Sociales a Inmigrantes: Casos Documentados",
		//"istorias de Acoso a Inmigrantes en Centros de Refugiados",
		//"coso Laboral a Inmigrantes en el Sector Agrícola",
		//"estimonios de Acoso a Inmigrantes en América Latina",
		//"elatos de Inmigrantes Víctimas de Acoso en el Trabajo",
		//"coso a Inmigrantes en Comunidades Virtuales: Historias Reales",
		//"istorias de Acoso a Inmigrantes en Países Europeos",
		//"coso en Universidades a Estudiantes Inmigrantes",
		//"elatos de Acoso a Inmigrantes en la Construcción",
		//"estimonios de Acoso a Inmigrantes en el Transporte Público en Europa",
		//"coso en Escuelas a Hijos de Inmigrantes: Historias Reales",
		//"asos de Acoso a Inmigrantes en el Ámbito Sanitario",
		//"istorias de Inmigrantes Víctimas de Acoso en el Servicio Doméstico",
		//"elatos de Acoso en Centros de Detención de Inmigrantes",
		//"coso a Inmigrantes en Redes Sociales: Impacto Psicológico",
		//"istorias de Acoso a Inmigrantes en Países de Acogida",
		//"estimonios de Acoso a Inmigrantes en Zonas Fronterizas",
		//"elatos de Inmigrantes Víctimas de Acoso en Centros Educativos",
		//"coso en el Trabajo a Inmigrantes en Países Desarrollados",
		//"istorias de Acoso a Inmigrantes en Redes Sociales",
		//"estimonios de Acoso a Inmigrantes en el Ámbito Laboral",
		//"coso a Inmigrantes en el Transporte Público: Relatos Reales",
		//"istorias de Inmigrantes Víctimas de Acoso en América Latina",
		//"coso a Inmigrantes en Comunidades Online: Consecuencias Emocionales",
		//"elatos de Acoso en Lugares de Trabajo a Inmigrantes",
		//"estimonios de Acoso a Inmigrantes en Escuelas de Países de Acogida",
		//"coso a Inmigrantes en el Sector Servicios: Historias Reales",
		//"elatos de Inmigrantes Víctimas de Acoso en Países Europeos",
		//"istorias de Acoso a Inmigrantes en Entornos Laborales Hostiles",
		//"estimonios de Acoso a Inmigrantes en Espacios Públicos",
		//"coso a Inmigrantes en Países Desarrollados: Casos Documentados",
		//"elatos de Acoso a Inmigrantes en el Ámbito Escolar",
		//"istorias de Acoso a Inmigrantes en la Construcción y Agricultura",
		//"estimonios de Acoso a Inmigrantes en Oficinas Gubernamentales",
		//"coso a Inmigrantes en Entornos Urbanos: Relatos Impactantes",
		//"istorias de Inmigrantes Víctimas de Acoso en Redes Sociales",
		//"estimonios de Acoso a Inmigrantes en Centros de Detención",
		//"¿Qué es el acoso?",
		//"Tipos de acoso",
		//"Definición de acoso escolar",
		//"Causas del acoso",
		//"Efectos del acoso en la víctima",
		//"Consecuencias legales del acoso",
		//"Acoso físico vs acoso psicológico",
		//"Cómo identificar el acoso",
		//"Prevención del acoso",
		//"Acoso cibernético o cyberbullying",
		//"Acoso laboral: definición y ejemplos",
		//"Señales de acoso en el trabajo",
		//"Leyes contra el acoso laboral",
		//"Diferencia entre acoso y bullying",
		//"Acoso sexual: qué es y cómo prevenirlo",
		//"Casos famosos de acoso sexual",
		//"Acoso en redes sociales",
		//"Cómo denunciar el acoso",
		//"Protocolo ante situaciones de acoso",
		//"Cómo actuar frente al acoso escolar",
		//"Acoso escolar: guías para padres y maestros",
		//"Acoso en adolescentes: causas y prevención",
		//"Cómo afecta el acoso a la salud mental",
		//"Víctimas de acoso: cómo brindar apoyo",
		//"Estrategias para superar el acoso",
		//"Perfiles de acosadores",
		//"Acoso en línea: medidas de protección",
		//"Impacto del acoso en el rendimiento escolar",
		//"Acoso entre compañeros de trabajo",
		//"Acoso escolar: estrategias de intervención",
		//"Cyberbullying: casos y estudios",
		//"Cómo evitar ser víctima de acoso en redes sociales",
		//"El impacto del acoso en niños y adolescentes",
		//"Acoso laboral: cómo afrontarlo legalmente",
		//"Acoso en el ámbito académico",
		//"Testimonios de víctimas de acoso",
		//"Acoso y la influencia de la cultura digital",
		//"Programas de concienciación sobre el acoso",
		//"Dinámicas de poder en el acoso",
		//"¿Cómo afecta el acoso a la autoestima?",
		//"Psicología del acosador",
		//"Tratamiento psicológico para víctimas de acoso",
		//"Acoso y violencia de género",
		//"Estrategias para evitar el acoso escolar",
		//"Cómo el acoso afecta la vida adulta",
		//"Cómo identificar un ambiente laboral tóxico",
		//"Redes de apoyo para víctimas de acoso",
		//"Impacto social del acoso en el entorno laboral",
		//"Cómo el acoso afecta la productividad laboral",
		//"Recursos para prevenir el acoso en instituciones educativas",
		//"¿Qué es el ciberacoso?",
		//"Tipos de ciberacoso",
		//"Diferencias entre ciberacoso y bullying tradicional",
		//"Consecuencias psicológicas del ciberacoso",
		//"Cómo identificar el ciberacoso en redes sociales",
		//"Ejemplos de ciberacoso en plataformas digitales",
		//"Herramientas para prevenir el ciberacoso",
		//"Cómo denunciar el ciberacoso",
		//"Ciberacoso en adolescentes: casos y estadísticas",
		//"Leyes contra el ciberacoso en diferentes países",
		//"Estrategias para protegerse del ciberacoso",
		//"Ciberacoso a través de mensajes de texto",
		//"Señales de ciberacoso en menores de edad",
		//"Cómo el ciberacoso afecta la salud mental",
		//"Ciberacoso en foros y chats online",
		//"Medidas de seguridad para evitar el ciberacoso",
		//"Ciberacoso y anonimato en internet",
		//"Cómo afecta el ciberacoso a la autoestima",
		//"El impacto del ciberacoso en la sociedad",
		//"Casos famosos de ciberacoso y sus consecuencias",
		//"Efectos del ciberacoso a largo plazo",
		//"Qué hacer si eres víctima de ciberacoso",
		//"Prevención del ciberacoso en redes sociales",
		//"Acoso en línea vs acoso presencial",
		//"Perfil psicológico del ciberacosador",
		//"Cómo proteger a los adolescentes del ciberacoso",
		//"Impacto del ciberacoso en el rendimiento académico",
		//"Consecuencias legales del ciberacoso en menores",
		//"Ciberacoso y el papel de las plataformas sociales",
		//"Estudios sobre la prevalencia del ciberacoso",
		//"Ciberacoso a famosos: casos y análisis",
		//"Campañas de concienciación sobre el ciberacoso",
		//"Efectos del ciberacoso en la vida adulta",
		//"Ciberacoso en aplicaciones de mensajería instantánea",
		//"Cómo prevenir el ciberacoso en juegos online",
		//"Testimonios de víctimas de ciberacoso",
		//"Cómo las redes sociales responden al ciberacoso",
		//"Estrategias legales para combatir el ciberacoso",
		//"Factores de riesgo en el ciberacoso",
		//"Métodos de ciberacoso más comunes",
		//"Ciberacoso en plataformas de video y streaming",
		//"Rol de los padres en la prevención del ciberacoso",
		//"Ciberacoso entre compañeros de escuela",
		//"Cómo afecta el ciberacoso la reputación online",
		//"Ciberacoso y difamación: diferencias y semejanzas",
		//"Herramientas tecnológicas para detectar ciberacoso",
		//"Protocolos de actuación en casos de ciberacoso",
		//"Cómo educar a los niños sobre el ciberacoso",
		//"El papel de los influencers en la lucha contra el ciberacoso",
		//"Consejos para evitar el ciberacoso en el entorno laboral",
		//"Efectos a largo plazo del acoso en adultos",
		//"Consecuencias del acoso en la salud física y emocional",
		//"Técnicas psicológicas para tratar a víctimas de acoso",
		//"Impacto del acoso en la identidad personal",
		//"Estrategias legales para combatir el acoso",
		//"Acoso entre compañeros de clase: estudios psicológicos",
		//"Terapia cognitivo-conductual para víctimas de acoso",
		//"Relación entre el acoso y el trastorno de estrés postraumático",
		//"Acoso entre géneros: diferencias en víctimas y agresores",
		//"Estudio de casos de acoso en el entorno educativo",
		//"Rol de la tecnología en el aumento del acoso",
		//"Comportamiento social en el acoso grupal",
		//"Factores socioculturales que influyen en el acoso",
		//"Perfiles psicológicos de acosadores en serie",
		//"Acoso en la infancia y sus efectos en la adultez",
		//"Rol del bystander en situaciones de acoso",
		//"Cómo el acoso afecta el desarrollo cognitivo en niños",
		//"Círculo vicioso del acoso: víctima convertida en acosador",
		//"Acoso y exclusión social: estudios sociológicos",
		//"Acoso sexual en el lugar de trabajo: estudios recientes",
		//"Impacto del acoso en el bienestar psicológico de adolescentes",
		//"Estrategias de afrontamiento para víctimas de acoso",
		//"Rol de la empatía en la prevención del acoso",
		//"Acoso en instituciones educativas: casos y políticas",
		//"Estrategias de intervención ante el acoso en escuelas",
		//"Efectos del acoso en la autoconfianza y la autoestima",
		//"Modelos de intervención en acoso laboral",
		//"Programas de rehabilitación para acosadores",
		//"Métodos de mediación en casos de acoso escolar",
		//"Papel de los padres en la prevención del acoso",
		//"Causas psicológicas del acoso entre adolescentes",
		//"Percepción social del acoso en el siglo XXI",
		//"Acoso entre compañeros de trabajo: análisis de casos",
		//"Impacto económico del acoso en el entorno laboral",
		//"Cómo el acoso escolar afecta las habilidades sociales",
		//"Técnicas de resolución de conflictos en casos de acoso",
		//"Acoso y desigualdad de poder en las relaciones humanas",
		//"Acoso en instituciones militares: análisis y prevención",
		//"Factores de riesgo asociados al acoso escolar",
		//"Cómo crear entornos laborales libres de acoso",
		//"Estereotipos de género en el acoso sexual",
		//"Legislación internacional sobre el acoso laboral",
		//"Acoso entre hermanos: un problema no reconocido",
		//"Técnicas de educación emocional para prevenir el acoso",
		//"Impacto del acoso en la productividad laboral",
		//"Cómo los medios de comunicación abordan el acoso",
		//"Relación entre acoso y trastornos de ansiedad",
		//"Acoso psicológico: diferencias con el acoso físico",
		//"Programas de sensibilización sobre el acoso en jóvenes",
		//"Evaluación del impacto del acoso en la dinámica familiar",
		//"Cómo identificar un caso de ciberacoso",
		//"Perfil del ciberacosador: análisis psicológico",
		//"Consecuencias del ciberacoso en la salud mental",
		//"Impacto del ciberacoso en la vida digital y personal",
		//"Acoso en redes sociales: cómo detectarlo y prevenirlo",
		//"Herramientas de monitoreo para ciberacoso en menores",
		//"Relación entre ciberacoso y trastornos de ansiedad",
		//"Ciberacoso en adolescentes: estrategias de prevención",
		//"Casos de ciberacoso en escuelas: análisis de casos reales",
		//"Cómo el ciberacoso afecta la identidad digital",
		//"Ciberacoso en grupos de WhatsApp y aplicaciones de mensajería",
		//"Rol del anonimato en el aumento del ciberacoso",
		//"Diferencias entre ciberacoso y trolling",
		//"Impacto del ciberacoso en la autoestima de los adolescentes",
		//"Estrategias legales para combatir el ciberacoso",
		//"Cómo se utiliza la tecnología para llevar a cabo el ciberacoso",
		//"Ciberacoso en plataformas de video como YouTube y TikTok",
		//"Efectos del ciberacoso en la reputación online",
		//"El papel de las plataformas sociales en el ciberacoso",
		//"Prevención del ciberacoso en aplicaciones móviles",
		//"Acoso digital y leyes de protección de datos",
		//"Ciberacoso en el ámbito laboral: casos y estrategias",
		//"Cómo afecta el ciberacoso al rendimiento académico",
		//"El impacto del ciberacoso en la vida adulta",
		//"Ciberacoso en el gaming: acoso en comunidades de videojuegos",
		//"Análisis de casos judiciales sobre ciberacoso",
		//"Ciberacoso en menores: cómo proteger a los niños online",
		//"Métodos de intervención en casos de ciberacoso",
		//"El papel de los padres en la prevención del ciberacoso",
		//"Herramientas tecnológicas para denunciar el ciberacoso",
		//"Impacto emocional del ciberacoso en jóvenes",
		//"Señales de ciberacoso en el entorno escolar",
		//"Ciberacoso en influencers y creadores de contenido",
		//"Relación entre el ciberacoso y el sexting",
		//"Herramientas de seguridad para protegerse del ciberacoso",
		//"Psicología del ciberacosador: motivaciones y conductas",
		//"Cómo el ciberacoso afecta la privacidad online",
		//"Estrategias de redes sociales para combatir el ciberacoso",
		//"Casos de ciberacoso en famosos: consecuencias legales",
		//"Diferencias entre ciberacoso y acoso tradicional",
		//"Programas educativos para prevenir el ciberacoso",
		//"Técnicas de detección de ciberacoso en entornos virtuales",
		//"Impacto del ciberacoso en la identidad de género",
		//"Rol de las instituciones educativas en la prevención del ciberacoso",
		//"El papel de la inteligencia artificial en la lucha contra el ciberacoso",
		//"Dinámicas grupales en el ciberacoso: cómo se propaga en redes",
		//"Prevención del ciberacoso en entornos corporativos",
		//"Estudios recientes sobre la prevalencia del ciberacoso",
		//"Recursos para víctimas de ciberacoso",
		//"Acoso en el metaverso: nuevos desafíos del ciberacoso",
		//"Acoso escolar en academias: análisis y prevención",
		//"Bullying académico: estrategias de intervención",
		//"Cómo identificar y manejar el acoso en entornos educativos",
		//"Impacto del acoso en el rendimiento académico de los estudiantes",
		//"Prevención del acoso en escuelas y academias: mejores prácticas",
		//"Estrategias efectivas contra el bullying en instituciones educativas",
		//"Acoso entre alumnos: estudios de caso y soluciones",
		//"Acoso en entornos académicos: guía para educadores",
		//"Programas de prevención del acoso escolar en academias",
		//"Impacto psicológico del acoso en estudiantes: investigaciones recientes",
		//"Cómo combatir el acoso en el aula: enfoques y métodos",
		//"Acoso en la educación: políticas y procedimientos para academias",
		//"Investigaciones sobre el bullying en entornos académicos",
		//"Intervención temprana en casos de acoso escolar",
		//"Técnicas de resolución de conflictos para prevenir el acoso en academias",
		//"Acoso académico: herramientas para la identificación y apoyo",
		//"Protocolos de respuesta al acoso en instituciones educativas",
		//"Estrategias de apoyo para víctimas de bullying en academias",
		//"Análisis de políticas antiacoso en escuelas y academias",
		//"Estudios sobre la efectividad de las medidas contra el acoso escolar",
		//"Acoso en bachillerato y autoestima",
		//"Impacto del bullying en la autoestima adolescente",
		//"Mejorar la autoestima en estudiantes acosados",
		//"Relación entre acoso y autoestima en bachillerato",
		//"Efectos del acoso escolar en la autoestima",
		//"Apoyo para fortalecer la autoestima en víctimas de acoso",
		//"Autoestima baja por acoso en bachillerato",
		//"Prevención del acoso y autoestima en bachillerato",
		//"Autoestima y acoso en estudiantes de secundaria",
		//"Consejos sobre autoestima y bullying escolar",
		//"Acoso escolar y autoestima a largo plazo",
		//"Terapias para autoestima en jóvenes acosados",
		//"Programas de autoestima para víctimas de bullying",
		//"Acoso y autoestima en bachillerato: soluciones",
		//"Factores que afectan la autoestima por acoso",
		//"Apoyo en autoestima para estudiantes acosados",
		//"Estudios sobre autoestima y acoso escolar",
		//"Técnicas para mejorar la autoestima en acosados",
		//"Impacto del bullying en el rendimiento y autoestima",
		//"Prevención del acoso y desarrollo de autoestima",
		//"acoso en mexico",
		//"acoso en colombia",
		//"acoso en peru",
		//"acoso en ecuador",
		//"acoso en bolivia",
		//"ciberacoso en mexico",
		//"ciberacoso en colombia",
		//"ciberacoso en peru",
		//"ciberacoso en ecuador",
		//"2 de cada 10 han sufrido ciberacoso",
		//"1 de cada 5 estudiantes experimenta acoso escolar",
		//"3 de cada 10 adolescentes enfrentan bullying en bachillerato",
		//"2 de cada 10 jóvenes sufren acoso en línea",
		//"4 de cada 10 víctimas de acoso escolar tienen baja autoestima",
		//"1 de cada 4 estudiantes en bachillerato reporta acoso",
		//"3 de cada 5 adolescentes afectados por acoso tienen problemas de autoestima",
		//"2 de cada 10 jóvenes en bachillerato son acosados en redes sociales",
		//"1 de cada 3 estudiantes sufre bullying en su vida escolar",
		//"5 de cada 10 víctimas de acoso escolar muestran signos de depresión",
		//"2 de cada 10 adolescentes sufren acoso cibernético",
		//"4 de cada 10 estudiantes acosados tienen dificultades académicas",
		//"1 de cada 6 adolescentes enfrenta acoso en el aula",
		//"3 de cada 10 estudiantes en bachillerato experimentan bullying",
		//"2 de cada 5 jóvenes acosados tienen problemas de autoestima",
		//"1 de cada 4 estudiantes de secundaria sufre acoso en línea",
		//"5 de cada 10 jóvenes acosados en bachillerato necesitan apoyo psicológico",
		//"2 de cada 8 adolescentes sufren acoso cibernético",
		//"1 de cada 7 estudiantes tiene baja autoestima debido al bullying",
		//"3 de cada 10 víctimas de acoso escolar reportan ansiedad",
		//"2 de cada 5 jóvenes en bachillerato experimentan acoso en redes sociales",
		//"Guía sobre ciberacoso: prevención y respuesta",
		//"Estadísticas recientes sobre ciberacoso en adolescentes",
		//"Impacto del ciberacoso en la salud mental de los jóvenes",
		//"Infografía: Cómo identificar y manejar el ciberacoso",
		//"Video educativo sobre ciberacoso y sus efectos",
		//"Estudio de caso: Efectos del ciberacoso en estudiantes",
		//"Blog sobre estrategias para combatir el ciberacoso",
		//"Documental sobre historias de víctimas de ciberacoso",
		//"Informe de investigación sobre ciberacoso en redes sociales",
		//"Podcast: Consejos para prevenir el ciberacoso en adolescentes",
		//"Manual para padres sobre cómo enfrentar el ciberacoso",
		//"Curso en línea sobre ciberacoso y protección en internet",
		//"Análisis de políticas contra el ciberacoso en escuelas",
		//"Entrevistas con expertos en ciberacoso y seguridad en línea",
		//"Seminario web sobre el impacto del ciberacoso en la autoestima",
		//"Reseña de herramientas para la detección de ciberacoso",
		//"Encuesta sobre experiencias de ciberacoso entre adolescentes",
		//"Foro de discusión sobre ciberacoso y salud emocional",
		//"Manual para educadores sobre ciberacoso y prevención en línea",
		//"Comparativa de programas educativos sobre ciberacoso",
		//"Preguntas frecuentes sobre ciberacoso",
		//"Checklist para prevenir el ciberacoso en jóvenes",
		//"Tutorial sobre cómo reportar ciberacoso en redes sociales",
		//"Guía paso a paso para padres: cómo abordar el ciberacoso",
		//"Webinar sobre las consecuencias del ciberacoso en adolescentes",
		//"Recomendaciones de expertos sobre manejo del ciberacoso",
		//"Plantilla de informe para casos de ciberacoso",
		//"Lista de recursos y apoyo para víctimas de ciberacoso",
		//"Infografía interactiva sobre señales de ciberacoso",
		//"Mapa interactivo de incidencia de ciberacoso en diferentes regiones",
		//"Testimonios de adolescentes afectados por ciberacoso",
		//"Evaluación de riesgo de ciberacoso en entornos escolares",
		//"Serie de artículos sobre prevención del ciberacoso",
		//"Encuesta interactiva sobre el impacto del ciberacoso",
		//"Cuestionario para detectar signos de ciberacoso en jóvenes",
		//"Checklist para crear un entorno seguro contra el ciberacoso en el aula",
		//"Guía de recursos digitales para enfrentar el ciberacoso",
		//"Web app para monitorear y prevenir ciberacoso",
		//"Plantillas de talleres educativos sobre ciberacoso",
		//"Serie de videos educativos sobre ciberacoso en redes sociales",
		//"Checklist de acciones inmediatas tras un incidente de ciberacoso",
		//"Diagrama de flujo para la intervención en casos de ciberacoso",
		//"Plan de acción para combatir el ciberacoso en instituciones educativas",
		//"Calendario de actividades preventivas contra el ciberacoso",
		//"Plantillas de mensajes para educar sobre el ciberacoso",
		//"Muestra de materiales educativos sobre ciberacoso para talleres",
		//"Glosario de términos relacionados con el ciberacoso",
		//"Resumen ejecutivo sobre políticas contra el ciberacoso",
		//"Estudio comparativo de programas contra el ciberacoso",
		//"Infografía de mejores prácticas para la prevención del ciberacoso",
		//"Manual de usuario para herramientas anti-ciberacoso en redes sociales",
		//"Guía de conversación para hablar con adolescentes sobre ciberacoso",
		//"Video tutorial sobre herramientas de monitoreo de ciberacoso",
		//"Guía de resolución de conflictos relacionados con ciberacoso",
		//"Simulador de escenarios de ciberacoso para entrenar a educadores",
		//"Diario de casos de ciberacoso y sus soluciones",
		//"Informe anual sobre tendencias de ciberacoso en jóvenes",
		//"Manual para la formación de personal en prevención del ciberacoso",
		//"Guía rápida de señales de alerta de ciberacoso en adolescentes",
		//"Plantillas para entrevistas y sesiones de apoyo a víctimas de ciberacoso",
		//"Casos Reales de Ciberacoso en Adolescentes",
		//"Historias de Víctimas de Ciberacoso y su Impacto",
		//"Testimonios de Sobrevivientes del Ciberacoso",
		//"Casos de Ciberacoso en Redes Sociales: Facebook, Instagram y TikTok",
		//"Cómo el Ciberacoso Ha Afectado a Jóvenes Famosos",
		//"Casos Judiciales Famosos Relacionados con el Ciberacoso",
		//"Ciberacoso en el Ámbito Escolar: Casos y Soluciones",
		//"Historias de Ciberacoso en el Ámbito Laboral",
		//"Impacto Psicológico del Ciberacoso: Testimonios de Víctimas",
		//"Ciberacoso y sus Consecuencias: Historias Anónimas de Víctimas",
		//"Guía Actualizada de Prevención del Ciberacoso para Padres (2023)",
		//"Estrategias de Prevención del Ciberacoso en Escuelas (2024)",
		//"Consejos Modernos para Proteger a los Niños del Ciberacoso (2023-2024)",
		//"Cómo Evitar el Ciberacoso en Redes Sociales (2023)",
		//"Buenas Prácticas en el Ámbito Laboral para Prevenir el Ciberacoso (2024)",
		//"Educación Digital para Prevenir el Ciberacoso en 2023",
		//"Medidas Preventivas de Ciberacoso para Jóvenes en 2024",
		//"Campañas Efectivas para la Prevención del Ciberacoso (2023-2024)",
		//"Herramientas Tecnológicas Recientes para Prevenir el Ciberacoso",
		//"Programas Escolares de Prevención del Ciberacoso (2023-2024)",
		//"Señales Comunes de que Alguien Está Sufriendo Ciberacoso (2024)",
		//"Cómo Identificar el Ciberacoso en Redes Sociales en 2023",
		//"Características de los Agresores en Casos de Ciberacoso (2023)",
		//"Tipos de Ciberacoso y Cómo Reconocerlos en 2024",
		//"Cómo Distinguir una Broma de un Acto de Ciberacoso (2023)",
		//"Reconociendo el Ciberacoso en Grupos de Mensajería en 2024",
		//"Identificación del Ciberacoso en Plataformas de Videojuegos (2023)",
		//"Ciberacoso Anónimo: Cómo Detectarlo en 2024",
		//"Signos de Alerta en Niños que Pueden Estar Sufriendo Ciberacoso (2023)",
		//"Detección de Ciberacoso en Entornos Virtuales de Aprendizaje (2024)",
		//"Encuesta Global sobre el Impacto del Ciberacoso en Jóvenes (2023)",
		//"Estudio Estadístico sobre el Ciberacoso en América Latina (2023-2024)",
		//"Encuesta Nacional sobre Ciberacoso en Adolescentes (2024)",
		//"Estudios Académicos Recientes sobre las Causas del Ciberacoso (2023)",
		//"Encuestas de Uso de Redes Sociales y el Ciberacoso en 2024",
		//"Datos Estadísticos Recientes sobre el Ciberacoso en Niños (2023)",
		//"Informe sobre el Ciberacoso en el Ámbito Laboral en 2024",
		//"Resultados Globales de Encuestas sobre Ciberacoso Escolar (2023-2024)",
		//"Estudios Psicológicos sobre las Consecuencias del Ciberacoso (2024)",
		//"Encuestas Recientes sobre Ciberacoso en Videojuegos en Línea (2023)",
		//"Cifras Recientes del Ciberacoso en América Latina (2023-2024)",
		//"Porcentajes de Víctimas de Ciberacoso en Diferentes Países (2023)",
		//"Estadísticas Recientes sobre el Ciberacoso en Adolescentes (2024)",
		//"Diferencias de Género en Ciberacoso: Estadísticas 2023",
		//"Porcentaje de Casos de Ciberacoso en Escuelas (2023)",
		//"Informe de la ONU sobre Ciberacoso en el Año 2024",
		//"Estadísticas sobre el Ciberacoso en el Ámbito Laboral (2023)",
		//"Ciberacoso en la Educación: Estadísticas Escolares en 2024",
		//"Impacto del Ciberacoso en la Salud Mental: Datos Recientes (2023)",
		//"Ciberacoso y Suicidio: Estadísticas Alarmantes del 2024",
		//"Ciberacoso en Estados Unidos: Análisis de Casos en 2024",
		//"Ciberacoso en el Reino Unido: Datos Recientes y Prevención (2023)",
		//"Situación del Ciberacoso en Japón y Corea del Sur (2023-2024)",
		//"Ciberacoso en América Latina: Informe de 2023",
		//"Ciberacoso en España: Nuevas Estadísticas y Casos (2024)",
		//"Informe sobre el Ciberacoso en Australia (2023-2024)",
		//"Países Europeos con Más Casos de Ciberacoso en 2023",
		//"El Ciberacoso en India: Nuevos Retos y Respuestas (2024)",
		//"Impacto del Ciberacoso en África: Datos Recientes (2023)",
		//"El Ciberacoso en Medio Oriente: Casos y Regulaciones (2023-2024)",
		//"Ciberacoso en Redes Sociales: Plataformas Afectadas en 2023",
		//"Aumento del Ciberacoso en Videojuegos en Línea (2024)",
		//"Ciberacoso en Foros de Internet: Casos Recientes (2023)",
		//"Ciberacoso en Aplicaciones de Mensajería Instantánea (2024)",
		//"El Rol de las Plataformas de Video en el Aumento del Ciberacoso (2023)",
		//"Casos de Ciberacoso en Grupos Privados de Redes Sociales (2024)",
		//"Plataformas de Educación en Línea y el Riesgo de Ciberacoso (2023)",
		//"Plataformas de Video en Vivo y el Ciberacoso (2024)",
		//"Ciberacoso en Blogs y Foros de Opinión (2023-2024)",
		//"Ciberacoso en Comunidades Online de Videojuegos (2023)",
		//"Publicación de Imágenes Privadas sin Permiso: Ciberacoso en 2023",
		//"Amenazas en Línea: Casos Relevantes en 2024",
		//"Difamación en Redes Sociales en 2023: Un Acto de Ciberacoso",
		//"El Flaming en Foros y Redes Sociales (2024)",
		//"Envío de Mensajes Amenazantes: Un Caso de Ciberacoso (2023)",
		//"Hostigamiento Anónimo en Plataformas Digitales (2023-2024)",
		//"Ciberacoso en Grupos Escolares de Mensajería (2023)",
		//"Suplantación de Identidad en Casos de Ciberacoso en 2024",
		//"Sexting no Consentido: Un Caso de Ciberacoso (2023)",
		//"Acoso Persistente en Videojuegos en Línea (2024)",
		//"Cyberbullying vs Ciberacoso: Diferencias en 2023",
		//"Troleo en Internet: Una Forma de Ciberacoso en Aumento (2024)",
		//"Doxxing: Publicación de Datos Privados en 2023",
		//"Stalking Virtual: Cómo Identificarlo en 2024",
		//"El Catfishing como Forma de Ciberacoso en 2023",
		//"Grooming en Internet: Casos y Prevención en 2024",
		//"Ciberacoso Colectivo: Tendencias Recientes en 2023",
		//"Swatting: Peligroso Ciberacoso en 2024",
		//"Acoso en Chats de Videojuegos: Nuevos Casos (2023)",
		//"Manipulación Psicológica en el Ciberacoso (2024)",
		//"Impacto Psicológico del Ciberacoso en Adolescentes (2023)",
		//"Consecuencias a Largo Plazo del Ciberacoso en Niños (2024)",
		//"Ciberacoso y Suicidio: Casos Trágicos en 2023",
		//"Efectos Emocionales del Ciberacoso en Víctimas Jóvenes (2024)",
		//"El Aislamiento Social Como Consecuencia del Ciberacoso (2023)",
		//"Daños en la Autoestima de las Víctimas del Ciberacoso (2023-2024)",
		//"Problemas de Ansiedad y Depresión Causados por el Ciberacoso (2024)",
		//"Consecuencias Legales del Ciberacoso en Diferentes Países (2023)",
		//"Cómo el Ciberacoso Afecta la Vida Académica y Social de los Jóvenes (2024)",
		//"Impacto del Ciberacoso en el Desempeño Escolar: Estudios Recientes (2023)",
		//"Cómo las Redes Sociales Fomentan el Ciberacoso en 2024",
		//"El Rol de los Influencers en la Prevención del Ciberacoso (2023)",
		//"Tendencias de Ciberacoso en TikTok y Otras Redes Sociales (2024)",
		//"Casos de Ciberacoso en Instagram: Prevención en 2023",
		//"Ciberacoso en Grupos de Facebook: Medidas Tomadas en 2024",
		//"Plataformas Emergentes y el Aumento del Ciberacoso en 2023",
		//"Ciberacoso en Twitter: Medidas de Seguridad en 2024",
		//"El Efecto del Ciberacoso en las Comunidades de Reddit (2023)",
		//"La Cultura de Cancelación y el Ciberacoso en Redes Sociales (2023-2024)",
		//"Herramientas para Reportar Ciberacoso en Redes Sociales (2023)",
		//"Cómo Proteger tu Privacidad en Línea del Ciberacoso (2023)",
		//"Nuevas Regulaciones de Privacidad Digital contra el Ciberacoso (2024)",
		//"Herramientas de Seguridad Digital para Evitar el Ciberacoso (2023)",
		//"Ciberacoso y Exposición de Datos Personales en 2024",
		//"Privacidad y Anonimato en Línea: Retos para el 2023",
		//"Prevención de Ciberacoso en Aplicaciones de Mensajería Privada (2024)",
		//"El Impacto de las Leyes de Privacidad en la Reducción del Ciberacoso (2023)",
		//"Cómo Manejar el Robo de Identidad en Casos de Ciberacoso (2024)",
		//"Cambios en la Legislación de Privacidad para Prevenir el Ciberacoso (2023)",
		//"Nuevas Herramientas para Proteger la Privacidad de los Usuarios en 2024",
		//"El Impacto del Ciberacoso en la Salud Mental de los Jóvenes (2023)",
		//"Ansiedad y Depresión Relacionadas con el Ciberacoso en 2024",
		//"Terapias en Línea para Víctimas de Ciberacoso (2023)",
		//"Cómo el Ciberacoso Afecta la Salud Mental de los Adolescentes (2024)",
		//"El Aumento de los Trastornos de Ansiedad debido al Ciberacoso (2023)",
		//"Ciberacoso y su Relación con el Suicidio en Jóvenes (2023-2024)",
		//"Herramientas Psicológicas para Combatir los Efectos del Ciberacoso (2024)",
		//"Cómo el Ciberacoso Influye en la Autoestima de los Adolescentes (2023)",
		//"Terapias Cognitivas para Víctimas de Ciberacoso (2024)",
		//"Los Impactos Emocionales del Ciberacoso en Niños y Adolescentes (2023)",
		//"Cómo la Inteligencia Artificial Está Siendo Utilizada para Combatir el Ciberacoso (2024)",
		//"Machine Learning para Detectar y Prevenir el Ciberacoso en Tiempo Real (2023)",
		//"El Rol de los Algoritmos en la Detección de Ciberacoso en Redes Sociales (2024)",
		//"Aplicaciones de Inteligencia Artificial para Identificar el Ciberacoso (2023)",
		//"Tecnología Blockchain para Proteger Contra el Ciberacoso en 2024",
		//"Soluciones Basadas en Inteligencia Artificial para Reducir el Ciberacoso en 2023",
		//"Chatbots y su Uso en la Prevención del Ciberacoso (2024)",
		//"Big Data y la Lucha Contra el Ciberacoso en Plataformas Digitales (2023)",
		//"Realidad Virtual y el Riesgo de Ciberacoso en el Metaverso (2024)",
		//"Nuevas Tecnologías para la Prevención de Ciberacoso Escolar (2023)",
		//"Nuevas Leyes Contra el Ciberacoso en Europa (2023-2024)",
		//"Legislación Actualizada para Combatir el Ciberacoso en Estados Unidos (2023)",
		//"Medidas Legislativas en América Latina para Prevenir el Ciberacoso (2024)",
		//"Nuevas Políticas Escolares contra el Ciberacoso en 2023",
		//"Avances en la Legislación Global Contra el Ciberacoso en 2024",
		//"Nuevas Multas y Penalidades para Casos de Ciberacoso en 2023",
		//"Legislación Sobre el Uso de Redes Sociales para Evitar el Ciberacoso (2024)",
		//"Leyes de Privacidad y Ciberacoso: ¿Cómo Están Cambiando en 2023?",
		//"Las Mejores Prácticas Jurídicas en la Lucha Contra el Ciberacoso (2024)",
		//"Legislación Internacional para Proteger a los Jóvenes del Ciberacoso (2023)",
		//"El Papel de la Educación Digital en la Prevención del Ciberacoso (2024)",
		//"Programas Escolares en 2023 para Combatir el Ciberacoso",
		//"Plataformas Educativas para Concienciar Sobre el Ciberacoso (2023)",
		//"Cómo las Escuelas Están Implementando Estrategias Anti-Ciberacoso (2024)",
		//"Formación en Seguridad Digital para Prevenir el Ciberacoso (2023)",
		//"El Uso de la Educación Digital en la Lucha Contra el Ciberacoso en 2024",
		//"Creación de Conciencia sobre el Ciberacoso en Programas Educativos (2023)",
		//"Educación para Padres y Alumnos sobre los Peligros del Ciberacoso (2024)",
		//"Cursos y Talleres en Línea para Prevenir el Ciberacoso (2023)",
		//"El Papel de los Profesores en la Prevención del Ciberacoso Escolar (2024)",
		//"El Efecto de la Cultura Digital en el Aumento del Ciberacoso (2023)",
		//"Cómo la Cultura de Cancelación se Relaciona con el Ciberacoso (2024)",
		//"Las Redes Sociales y el Aumento del Ciberacoso en la Cultura Pop (2023)",
		//"Ciberacoso y Cultura Juvenil: Cómo Combatirlo en 2024",
		//"El Papel de los Medios en la Promoción de la Conciencia sobre el Ciberacoso (2023)",
		//"Cómo los Estereotipos en Línea Contribuyen al Ciberacoso en 2024",
		//"El Ciberacoso en la Cultura de los Videojuegos en 2023",
		//"El Impacto del Ciberacoso en la Cultura de Internet (2023-2024)",
		//"Movimientos Sociales contra el Ciberacoso en la Era Digital (2023)",
		//"La Cultura del “Shaming” en Internet y el Ciberacoso en 2024",
		//"Cómo las Empresas Están Combatiendo el Ciberacoso en el Lugar de Trabajo (2023)",
		//"Políticas Corporativas Contra el Ciberacoso en 2024",
		//"El Ciberacoso Laboral en la Era del Trabajo Remoto (2023)",
		//"Estrategias de las Empresas para Prevenir el Ciberacoso (2024)",
		//"El Rol de los Recursos Humanos en Casos de Ciberacoso Laboral (2023)",
		//"El Impacto del Ciberacoso en la Productividad Laboral (2023-2024)",
		//"Cómo las Plataformas de Trabajo en Línea Manejan el Ciberacoso en 2024",
		//"Protocolos Corporativos para Evitar el Ciberacoso en 2023",
		//"Casos de Ciberacoso en el Ámbito Corporativo: Soluciones en 2024",
		//"Medidas de Protección Contra el Ciberacoso en el Trabajo Remoto (2023)",
		//"El Ciberacoso Dirigido a Mujeres: Datos Recientes de 2024",
		//"Cómo el Ciberacoso Afecta a las Minorías de Género en 2023",
		//"Casos de Ciberacoso hacia Personas LGBTQ+ en 2023",
		//"Estrategias para Combatir el Ciberacoso Basado en el Género en 2024",
		//"El Impacto del Ciberacoso en las Mujeres Jóvenes (2023-2024)",
		//"Ciberacoso y Misoginia en las Redes Sociales: Un Problema en 2023",
		//"Cómo la Tecnología Está Ayudando a Combatir el Ciberacoso de Género (2024)",
		//"El Papel de los Movimientos Feministas en la Lucha Contra el Ciberacoso (2023)",
		//"Cómo las Víctimas Femeninas de Ciberacoso Están Alzando la Voz en 2024",
		//"Estudios Sobre el Ciberacoso en Mujeres Influencers (2023)",
		//"La Brecha de Género en el Ciberacoso: Casos y Soluciones (2024)",
		//"El Impacto del Ciberacoso de Género en Adolescentes (2023)",
		//"Iniciativas Globales para Proteger a las Mujeres del Ciberacoso (2024)",
		//"El Ciberacoso en Niñas y Jóvenes: Datos Actualizados de 2023",
		//"Cómo las Plataformas Digitales Están Abordando el Ciberacoso de Género (2024)",
		//"Programas de Apoyo para Mujeres Víctimas de Ciberacoso (2023)",
		//"Casos de Ciberacoso en el Ámbito Político hacia Mujeres (2023-2024)",
		//"Cómo las Redes Sociales Pueden Reducir el Ciberacoso hacia Mujeres en 2024",
		//"Proyectos Tecnológicos para Combatir el Ciberacoso Basado en el Género (2023)",
		//"El Aumento del Ciberacoso en las Redes Sociales (2024)",
		//"Cómo Afecta el Ciberacoso a la Salud Mental de los Adolescentes (2023)",
		//"Legislaciones Recientes Contra el Ciberacoso en Diversos Países (2024)",
		//"El Rol de los Influencers en la Prevención del Ciberacoso (2024)",
		//"Estrategias de las Plataformas Digitales para Frenar el Ciberacoso (2023)",
		//"Estudio de Casos de Ciberacoso en Entornos Educativos (2024)",
		//"La Evolución del Ciberacoso en el Ámbito Laboral (2023)",
		//"La Relación Entre Ciberacoso y Suicidio en Jóvenes (2024)",
		//"El Ciberacoso Durante la Pandemia: Impacto en la Educación Virtual (2023)",
		//"Cómo Proteger a los Niños del Ciberacoso en el Mundo Digital (2024)",
		//"Herramientas de IA para Detectar y Prevenir el Ciberacoso (2023)",
		//"Proyectos Globales para Combatir el Ciberacoso en 2024",
		//"Ciberacoso y Delitos Digitales: Nuevas Amenazas en Línea (2023)",
		//"El Efecto del Ciberacoso en las Relaciones Familiares (2024)",
		//"El Impacto del Ciberacoso en la Autoestima de las Víctimas (2024)",
		//"Ciberacoso en los Videojuegos: Casos Recientes (2023)",
		//"Métodos Innovadores para Monitorear el Ciberacoso en Tiempo Real (2024)",
		//"El Ciberacoso en el Trabajo Remoto: Desafíos Actuales (2023)",
		//"La Expansión del Ciberacoso en Plataformas de Mensajería Instantánea (2024)",
		//"Ciberacoso y Diversidad: Cómo Afecta a Grupos Minoritarios (2023)",
		//"Nuevas Políticas de Protección Contra el Ciberacoso en Europa (2024)",
		//"Estudios Recientes Sobre la Psicología del Ciberacoso (2023)",
		//"El Ciberacoso Entre Parejas Jóvenes: Señales y Prevención (2024)",
		//"Cómo las Celebridades Están Luchando Contra el Ciberacoso (2024)",
		//"El Ciberacoso y la Cultura de Cancelación: ¿Cuál es la Diferencia? (2023)",
		//"Ciberacoso en las Elecciones: Manipulación y Ataques Personales (2024)",
		//"Cómo el Ciberacoso Puede Escalar a Amenazas Físicas (2023)",
		//"La Violencia Digital Contra las Mujeres: Un Problema Global (2024)",
		//"Casos Recientes de Ciberacoso en la Industria del Entretenimiento (2023)",
		//"El Impacto del Ciberacoso en el Desempeño Escolar (2024)",
		//"Técnicas de Autoayuda para Víctimas de Ciberacoso (2023)",
		//"Cómo las Redes Sociales Fomentan el Ciberacoso Anónimo (2024)",
		//"Programas Escolares para la Prevención del Ciberacoso en 2023",
		//"Cómo las Grandes Tecnológicas Están Enfrentando el Ciberacoso (2024)",
		//"Ciberacoso y Derechos Humanos: ¿Qué Cambios Son Necesarios? (2023)",
		//"El Ciberacoso y el Acoso Sexual: Donde Convergen (2024)",
		//"El Uso de la Realidad Aumentada en la Prevención del Ciberacoso (2023)",
		//"Qué Hacer si Eres Víctima de Ciberacoso: Consejos y Recursos (2024)",
		//"Cómo el Ciberacoso Impacta a las Personas con Discapacidades (2023)",
		//"Historias de Superación de Víctimas de Ciberacoso (2024)",
		//"La Relación Entre Ciberacoso y Ansiedad en Niños (2023)",
		//"Las Redes Sociales y la Propagación del Ciberacoso en Tiempo Real (2024)",
		//"La Participación de los Padres en la Prevención del Ciberacoso (2023)",
		//"Ciberacoso y Derechos Digitales: Un Debate en Curso (2024)",
		//"Cómo Reconocer el Ciberacoso en Foros Online (2023)",
		//"El Impacto del Ciberacoso en el Desarrollo Psicológico de los Jóvenes (2024)",
		//"Nuevos Métodos de Educación Digital para Combatir el Ciberacoso (2023)",
		//"La Ley y el Ciberacoso: Casos Judiciales Relevantes (2024)",
		//"Cómo la IA Está Ayudando a Identificar Casos de Ciberacoso (2023)",
		//"Ciberacoso en Aplicaciones de Citas: Cómo Protegerse (2024)",
		//"Cómo el Ciberacoso Afecta la Autoimagen en Redes Sociales (2023)",
		//"Medidas de Seguridad Cibernética para Evitar el Ciberacoso (2024)",
		//"Cómo el Ciberacoso Está Transformando la Interacción Social Online (2023)",
		//"Estudios Sociológicos Sobre el Ciberacoso en la Actualidad (2024)",
		//"El Papel de los Algoritmos en la Prevención del Ciberacoso (2023)",
		//"Cómo los Padres Pueden Ayudar a Sus Hijos a Evitar el Ciberacoso (2024)",
		//"Campañas Digitales Contra el Ciberacoso en 2023",
		//"Cómo las Universidades Están Abordando el Ciberacoso en Línea (2024)",
		//"El Ciberacoso y la Cultura del Odio en Línea (2023)",
		//"Recursos de Apoyo para Adolescentes Víctimas de Ciberacoso (2024)",
		//"El Papel de los Gobiernos en la Prevención del Ciberacoso (2023)",
		//"Cómo el Ciberacoso Puede Dañar las Carreras Profesionales (2024)",
		//"La Expansión del Ciberacoso a Través de Aplicaciones de Mensajería (2023)",
		//"Ciberacoso y el Uso de Falsos Perfiles: Cómo Detectarlo (2024)",
		//"El Impacto del Ciberacoso en la Autoexpresión Artística (2023)",
		//"Redes Sociales: Principales Plataformas donde Ocurre el Ciberacoso (2024)",
		//"Cómo las Escuelas Están Combatiendo el Ciberacoso a Nivel Global (2023)",
		//"El Ciberacoso y los Influencers: ¿Son más Vulnerables? (2024)",
		//"La Prevención del Ciberacoso en la Educación Online (2023)",
		//"Cómo las Marcas Están Luchando Contra el Ciberacoso en Publicidad (2024)",
		//"El Ciberacoso y la Exclusión Social en el Entorno Digital (2023)",
		//"Estrategias Psicológicas para Superar el Ciberacoso (2024)",
		//"Cómo las Herramientas de Análisis de Datos Identifican el Ciberacoso (2023)",
		//"La Evolución del Ciberacoso en los Últimos Años (2024)",
		//"Nuevos Avances Tecnológicos para Combatir el Ciberacoso en 2023",
		//"El Ciberacoso en el Mundo de los E-Sports: Un Problema Creciente (2024)",
		//"Cómo el Ciberacoso Puede Escalar a Crímenes de Odio (2023)",
		//"Estudios de Género y el Ciberacoso en Plataformas Digitales (2024)",
		//"El Ciberacoso Como Herramienta de Control Social en Línea (2023)",
		//"Iniciativas Internacionales para Detener el Ciberacoso en Niños (2024)",
		//"El Impacto del Ciberacoso en la Vida Universitaria (2023)",
		//"Cómo los Gobiernos Locales Están Enfrentando el Ciberacoso (2024)",
		//"Nuevas Técnicas de Machine Learning para Detectar el Ciberacoso (2023)",
		//"La Relación Entre Redes Anónimas y Ciberacoso (2024)",
		//"Ciberacoso en Aplicaciones Móviles: ¿Cómo Controlarlo? (2023)",
		//"El Efecto de los Comentarios Anónimos en el Ciberacoso (2024)",
		//"Cómo las Aplicaciones de Control Parental Previenen el Ciberacoso (2023)",
		//"La Psicología del Ciberacoso: Motivaciones y Comportamientos (2024)",
		//"Cómo las Instituciones de Salud Están Ayudando a Víctimas de Ciberacoso (2023)",
		//"Ciberacoso y Estrategias de Resiliencia para los Adolescentes (2024)",
		//"Nuevas Herramientas de Análisis de Sentimientos para Combatir el Ciberacoso (2023)",
		//"Cómo las Familias Están Enfrentando el Ciberacoso en Casa (2024)",
		//"Casos Recientes de Ciberacoso en Medios de Comunicación (2023)",
		//"Cómo las Plataformas de Streaming Están Combatiendo el Ciberacoso (2024)",
		//"El Ciberacoso Como Herramienta de Manipulación Política (2023)",
		//"Cómo las Empresas Tecnológicas Están Desarrollando Políticas Contra el Ciberacoso (2024)",
		//"Ciberacoso en Foros de Opinión: El Impacto en la Libertad de Expresión (2023)",
		//"Cómo los Algoritmos de Moderación Automática Detectan el Ciberacoso (2024)",
		//"El Rol del Anonimato en el Aumento del Ciberacoso (2023)",
		//"Ciberacoso y su Relación con la Delincuencia Juvenil (2024)",
		//"Cómo el Ciberacoso Agrava los Problemas Familiares (2024)",
		//"El Impacto del Ciberacoso en la Autoestima de Jóvenes Introvertidos (2024)",
		//"Ciberacoso y Vandalismo Digital: Nuevas Formas de Delincuencia (2024)",
		//"Del Ciberacoso al Vandalismo: Patrón Común entre Adolescentes (2024)",
		//"Cómo el Ciberacoso Puede Desencadenar Violencia en el Hogar (2024)",
		//"La Conexión entre Ciberacoso y el Aislamiento Social en Adolescentes (2024)",
		//"Estudios Recientes sobre Ciberacoso y Comportamientos Delictivos (2024)",
		//"Ciberacoso y Problemas Familiares: Factores de Riesgo (2024)",
		//"El Vandalismo Digital como Extensión del Ciberacoso en las Redes (2024)",
		//"Delincuencia Organizada y Ciberacoso: Tendencias en 2024",
		//"Cómo el Ciberacoso Puede Llevar a la Rebeldía Familiar y el Vandalismo (2024)",
		//"El Papel de la Introversión en la Vulnerabilidad al Ciberacoso (2024)",
		//"Ciberacoso y Familias Disfuncionales: Estudios Psicosociales (2024)",
		//"Nuevas Formas de Delincuencia Derivadas del Ciberacoso (2024)",
		//"Ciberacoso y Conflictos Familiares: Estadísticas y Casos en 2024",
		//"Cómo el Ciberacoso Alienta la Desconexión Social en Jóvenes Introvertidos (2024)",
		//"El Rol del Ciberacoso en el Aumento del Vandalismo Juvenil (2024)",
		//"Problemas Familiares como Causa y Consecuencia del Ciberacoso (2024)",
		//"Ciberacoso, Violencia Familiar y Riesgos para la Salud Mental (2024)",
		//"Cómo el Ciberacoso Fomenta el Desprecio por la Autoridad y el Vandalismo (2024)",
		//"Introversión y Ciberacoso: ¿Mayor Vulnerabilidad en 2024?",
		//"Ciberacoso y Familias Fragmentadas: Impacto Psicológico en Menores (2024)",
		//"El Vandalismo como Respuesta a Experiencias de Ciberacoso (2024)",
		//"La Delincuencia Virtual: Ciberacoso y Hacktivismo en 2024",
		//"Ciberacoso y la Estructura Familiar: Desafíos en la Sociedad Actual (2024)",
		//"La Relación entre Introversión y el Ciberacoso Persistente (2024)",
		//"Estudios sobre el Vandalismo Virtual y su Relación con el Ciberacoso (2024)",
		//"Familias con Miembros Víctimas de Ciberacoso: Consecuencias Sociales (2024)",
		//"Ciberacoso y Delincuencia Cibernética: Dos Caras de la Misma Moneda (2024)",
		//"Efectos del Ciberacoso en la Comunicación Familiar (2024)",
		//"Cómo el Aislamiento Familiar Incrementa el Riesgo de Ciberacoso (2024)",
		//"Comportamientos Delictivos Impulsados por el Ciberacoso: Un Estudio Global (2024)",
		//"Vandalismo y Ciberacoso: Cómo las Redes Sociales Promueven Ambos (2024)",
		//"Cómo el Ciberacoso Afecta las Relaciones Familiares (2024)",
		//"Ciberacoso y Reclusión Social: ¿Una Nueva Forma de Introversión? (2024)",
		//"Estudios Recientes sobre el Aumento de Vandalismo Digital en 2024",
		//"Ciberacoso y Delincuencia en Grupos Vulnerables (2024)",
		//"Ciberacoso y el Rol de los Padres en la Prevención de la Delincuencia (2024)",
		//"Cómo el Ciberacoso Influye en el Desarrollo de Comportamientos Delictivos (2024)",
		//"Ciberacoso y la Percepción de los Padres: Una Brecha Generacional (2024)",
		//"El Impacto del Ciberacoso en Niños Introvertidos: Consecuencias a Largo Plazo (2024)",
		//"Ciberacoso y Vandalismo: Estrategias para la Prevención en Comunidades (2024)",
		//"Cómo la Violencia Familiar Está Relacionada con el Ciberacoso (2024)",
		//"Del Ciberacoso al Cibercrimen: Un Escalamiento Preocupante (2024)",
		//"Cómo el Ciberacoso Aumenta la Tensión Familiar (2024)",
		//"El Papel del Vandalismo Digital en la Normalización del Ciberacoso (2024)",
		//"Ciberacoso y la Falta de Apoyo Familiar: Un Círculo Vicioso (2024)",
		//"Los Riesgos Psicológicos de los Jóvenes Introvertidos Ante el Ciberacoso (2024)",
		//"Nuevas Formas de Vandalismo Virtual Relacionadas con el Ciberacoso (2024)",
		//"Cómo el Ciberacoso Puede Convertirse en Delitos Reales (2024)",
		//"Ciberacoso y la Dinámica Familiar: Cómo Proteger a los Menores (2024)",
		//"La Introversión Como Factor de Riesgo en el Ciberacoso (2024)",
		//"El Papel del Ciberacoso en el Aumento de Delitos Juveniles (2024)",
		//"Cómo las Familias Pueden Afrontar el Ciberacoso para Evitar Problemas Mayores (2024)",
		//"Vandalismo y Ciberacoso: El Impacto en las Comunidades Locales (2024)",
		//"Estudios Recientes sobre la Delincuencia Cibernética Derivada del Ciberacoso (2024)",
		//"Cómo el Ciberacoso Deteriora la Comunicación en el Entorno Familiar (2024)",
		//"El Aislamiento Social de los Jóvenes y su Relación con el Ciberacoso (2024)",
		//"Ciberacoso, Vandalismo y el Impacto en la Convivencia Escolar (2024)",
		//"Estadísticas Actuales sobre Delincuencia Juvenil y Ciberacoso (2024)",
		//"Cómo el Ciberacoso Puede Destruir los Vínculos Familiares (2024)",
		//"El Vandalismo en Línea como Consecuencia de la Exclusión Social y el Ciberacoso (2024)",
		//"Ciberacoso y su Influencia en la Formación de Bandas Juveniles Delincuentes (2024)",
		//"Familias Afectadas por el Ciberacoso: Cómo Enfrentar el Problema en 2024",
		//"Cómo el Ciberacoso Puede Inducir al Vandalismo Digital (2024)",
		//"Ciberacoso y Jóvenes Introvertidos: Cómo Detectar Señales de Riesgo (2024)",
		//"Nuevas Formas de Vandalismo Virtual Promovidas por el Ciberacoso (2024)",
		//"El Ciberacoso y el Deterioro de la Salud Mental en Familias Conflictivas (2024)",
		//"Del Ciberacoso a la Criminalidad: Casos Documentados en 2024",
		//"Cómo el Ciberacoso Causa Desintegración Familiar (2024)",
		//"Vandalismo Digital y Ciberacoso: Problemas en la Sociedad Moderna (2024)",
		//"Cómo la Introversión Agrava la Experiencia del Ciberacoso (2024)",
		//"Familias con Problemas de Violencia y su Relación con el Ciberacoso (2024)",
		//"Ciberacoso y el Aumento de Delitos Cibernéticos en 2024",
		//"Vandalismo y Ciberacoso: Perspectivas de los Expertos para 2024",
		//"El Impacto del Ciberacoso en Familias con Problemas de Violencia Doméstica (2024)",
		//"Cómo el Ciberacoso Puede Llevar a la Conducta Delictiva (2024)",
		//"Ciberacoso y Aislamiento Familiar: Cómo Enfrentar el Problema en 2024",
		//"Cómo el Ciberacoso Fomenta el Vandalismo entre Jóvenes (2024)",
		//"La Conexión entre Ciberacoso y el Aumento de Delincuencia en Menores (2024)",
		//"Ciberacoso y Problemas Familiares: Cómo Romper el Ciclo (2024)",
		//"Cómo el Ciberacoso Potencia Actitudes Violentas en Jóvenes (2024)",
		//"Vandalismo y Ciberacoso: Un Problema en las Comunidades Virtuales (2024)",
		//"Efectos del Ciberacoso en Jóvenes Introvertidos y Vulnerables (2024)",
		//"Del Ciberacoso a la Violencia Física: Cómo Evitar la Escalada (2024)",
		//"Cómo el Ciberacoso Contribuye a la Desobediencia Familiar (2024)",
		//"Ciberacoso y Criminalidad Juvenil: Patrones y Soluciones en 2024",
		//"Vandalismo Digital: El Impacto de la Anonimidad en el Ciberacoso (2024)",
		//"El Papel de la Familia en la Prevención del Ciberacoso Juvenil (2024)",
		//"Ciberacoso, Aislamiento y la Formación de Grupos Delincuentes en 2024",
		//"Cómo la Introversión Agrava el Ciberacoso en Entornos Escolares (2024)",
		//"Vandalismo y Ciberacoso: Impacto en la Imagen de las Instituciones (2024)",
		//"Cómo el Ciberacoso Fragmenta las Relaciones Familiares (2024)",
		//"Delincuencia Juvenil y el Rol del Ciberacoso en la Era Digital (2024)",
		//"Cómo el Ciberacoso Alienta el Vandalismo en el Espacio Virtual (2024)",
		//"Familias con Hijos Víctimas de Ciberacoso: Estrategias para el 2024",
		//"Ciberacoso y Aislamiento Social: Riesgos de Delincuencia entre Jóvenes (2024)",
		//"Cómo el Ciberacoso y el Vandalismo Digital Están Conectados en 2024",
		//"Ciberacoso y Delincuencia Juvenil en Auge: Expertos Revelan Cómo Actuar a Tiempo (2024)",
		//"De las Redes Sociales al Vandalismo: Cómo el Ciberacoso Está Fomentando el Descontrol Juvenil (2024)",
		//"Problemas Familiares y Ciberacoso: Cómo Identificar y Frenar Este Ciclo Nocivo (2024)",
		//"Ciberacoso e Introversión: Un Peligroso Círculo Vicioso que Está Destruyendo a Nuestros Jóvenes (2024)",
		//"El Impacto del Ciberacoso en la Violencia Juvenil: Los Psicólogos Llaman a la Acción Urgente (2024)",
		//"Vandalismo y Ciberacoso, Dos Caras de la Misma Moneda: Qué Pueden Hacer los Padres para Prevenirlo (2024)",
		//"La Relación Entre el Ciberacoso y la Criminalidad Juvenil: Un Problema Alarma a las Autoridades (2024)",
		//"Aumento de Delincuencia Ligada al Ciberacoso: Qué Factores Desencadenan el Comportamiento Violento (2024)",
		//"De la Pantalla al Crimen: Cómo el Ciberacoso Está Formando a una Nueva Generación de Delincuentes (2024)",
		//"Ciberacoso y Desintegración Familiar: Psicólogos Explican Cómo Romper el Ciclo (2024)",
		//"El Aislamiento Provocado por el Ciberacoso: Cómo Reconocer las Señales de Peligro en Jóvenes (2024)",
		//"Vandalismo y Ciberacoso: Cómo las Redes Sociales Están Alimentando el Desorden en las Calles (2024)",
		//"La Escalada de Violencia por Ciberacoso: Cómo Actuar Antes de que Sea Demasiado Tarde (2024)",
		//"La Conexión Entre Familias Disfuncionales y el Ciberacoso: Lo Que No Sabías (2024)",
		//"Del Ciberespacio al Mundo Real: Cómo el Ciberacoso Está Incitando Actos de Vandalismo (2024)",
		//"El Ciberacoso en la Infancia y Adolescencia: Una Brecha que Puede Destruir Familias (2024)",
		//"Vandalismo Virtual y Ciberacoso: Cómo Están Cambiando las Normas en la Era Digital (2024)",
		//"El Impacto Silencioso del Ciberacoso en Jóvenes Introvertidos: Qué Pueden Hacer las Escuelas (2024)",
		//"Delincuencia Juvenil en la Era Digital: Cómo el Ciberacoso Está Alimentando el Problema (2024)",
		//"Ciberacoso y Problemas de Conducta: Cómo Proteger a los Jóvenes en un Mundo Digitalizado (2024)",
		//"Del Bullying en Línea a la Desobediencia Familiar: La Creciente Amenaza del Ciberacoso (2024)",
		//"De las Pantallas al Aislamiento Social: El Coste Invisible del Ciberacoso en los Jóvenes (2024)",
		//"Cómo el Ciberacoso Está Provocando Actos de Vandalismo y Delincuencia en Niños (2024)",
		//"Los Peligros del Ciberacoso y la Introversión: Qué Hacer Antes de que Sea Demasiado Tarde (2024)",
		//"Ciberacoso y Descomposición Familiar: Cómo las Redes Sociales Están Rompiendo Vínculos (2024)",
		//"El Efecto del Ciberacoso en Jóvenes Vulnerables: Cómo Evitar que se Convierta en Delincuencia (2024)",
		//"El Ciberacoso Como Precursor del Vandalismo: La Alarma en las Autoridades y Qué Hacer (2024)",
		//"Ciberacoso y Violencia Juvenil: Un Enlace que Necesita Ser Quebrado Urgentemente (2024)",
		//"Cómo el Ciberacoso Está Desencadenando Crisis Familiares: Señales que los Padres No Deben Ignorar (2024)",
		//"Ciberacoso y Aislamiento: Cómo las Redes Están Creando Jóvenes Vulnerables al Crimen (2024)",
		//"Vandalismo y Acoso en Línea: Cómo las Redes Sociales Facilitan la Conducta Violenta (2024)",
		//"La Influencia del Ciberacoso en el Aumento de la Criminalidad Juvenil: Estrategias de Prevención (2024)",
		//"Cómo el Ciberacoso Está Destruyendo Familias: Psicólogos Revelan las Consecuencias Invisibles (2024)",
		//"Del Ciberacoso al Delito: Cómo las Plataformas Sociales Están Fomentando Actos Criminales (2024)",
		//"De Víctima a Delincuente: El Círculo Vicioso del Ciberacoso en los Jóvenes (2024)",
		//"Ciberacoso y Desobediencia Familiar: Cómo las Redes Sociales Están Generando Conflictos en Casa (2024)",
		//"El Impacto del Ciberacoso en el Aislamiento Social: Una Amenaza en Crecimiento (2024)",
		//"Ciberacoso y Vandalismo Virtual: Cómo la Desinformación Está Alimentando el Caos (2024)",
		//"El Efecto Nocivo del Ciberacoso en Jóvenes Introvertidos: Qué Pueden Hacer los Padres y Maestros (2024)",
		//"Del Ciberacoso a la Criminalidad Juvenil: Un Camino que se Puede Prevenir (2024)",
		//"Ciberacoso y la Desintegración del Hogar: Cómo las Familias Están Siendo Afectadas (2024)",
		//"Vandalismo y Ciberacoso: Cómo la Tecnología Está Afectando el Comportamiento Juvenil (2024)",
		//"Cómo el Ciberacoso Contribuye al Aumento de Violencia Juvenil en las Ciudades (2024)",
		//"El Impacto del Ciberacoso en el Aislamiento y la Introversión de los Adolescentes (2024)",
		//"Ciberacoso y Desobediencia en el Hogar: El Rol de las Redes Sociales en la Dinámica Familiar (2024)",
		//"Ciberacoso y Aumento de Delincuencia Juvenil: Estrategias para Frenar esta Tendencia (2024)",
		//"Cómo el Ciberacoso Está Generando una Nueva Ola de Delitos Juveniles (2024)",
		//"El Vínculo Entre Ciberacoso y Actos de Vandalismo en Comunidades Urbanas (2024)",
		//"Ciberacoso y Desintegración Familiar: Lo que Debes Saber para Proteger a Tu Hijo (2024)",
		//"Cómo el Ciberacoso Afecta las Relaciones Familiares y Desencadena Violencia (2024)",
		//"El bullying y el ciberbullying están en aumento, alertan los pediatras: cómo abordar esta problemática",
	}
	dsn := "root:secret@tcp(127.0.0.1:3309)/acosoDB"
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	// Verificar la conexión
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Conexión exitosa a la base de datos.")
	now := time.Now()
	for _, topic := range topics {
		//Insert into database
		id := uuid.New().String()
		projectId := "91da2ca7-6244-11ef-9d2f-0242ac110002"
		_, errEx := db.Exec(
			"INSERT INTO scraped_topics (id, project_id,title,created_at) VALUES (?,?,?,?)",
			id,
			projectId,
			topic,
			now,
		)

		if errEx != nil {
			fmt.Println("Error: ", errEx)
			panic(err)
		}

	}
	fmt.Println("Se han migrado los temas correctamente.")
}
